<?php
/**
 * @file
 * Displays a block of configuration links in a Colorbox popup.
 */

/**
 * Implements hook_menu().
 */
function openpublic_splash_menu() {
  $items['splash/%openpublic_splash_block'] = array(
    'title' => '',
    'page callback' => 'openpublic_splash_block_display',
    'page arguments' => array(1),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/demo-toggle'] = array(
    'title' => 'Toggle demo content',
    'page callback' => 'openpublic_splash_toggle_demo_content',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}


/**
 * Implements hook_init().
 */
function openpublic_splash_init() {
  if (drupal_is_front_page()
      && user_access('administer site configuration')
      && !variable_get('openpublic_splash_welcome_seen', FALSE)) {
    $url = url('splash/site_welcome');
    $js = 'jQuery(document).ready(function () { jQuery.colorbox({ ';
    $js .= 'href: "' . $url . '",';
    $js .= 'width: 600,';
    $js .= 'height: 400,';
    $js .= 'opacity: .6,';
    $js .= '});});';
    drupal_add_js(drupal_get_path('module', 'openpublic_splash') . '/openpublic_splash.js');
    drupal_add_js($js, 'inline');

    // This makes it so that the splash page will never show up again, unless
    // this variable is set back to FALSE.
    variable_set('openpublic_splash_welcome_seen', TRUE);
  }
  $mod_uri = drupal_get_path('module', 'openpublic_splash');
  drupal_add_css( $mod_uri . '/openpublic_splash.css');

}


/**
 * Implements hook_block_info().
 */
function openpublic_splash_block_info() {
  $blocks['site_welcome'] = array(
    'info' => t('Welcome message splash screen'),
  );
  $blocks['site_config'] = array(
    'info' => t('Welcome message splash screen'),
    'status' => TRUE,
    'region' => 'dashboard_main',
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function openpublic_splash_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'site_welcome':
      $block['subject'] = t('Welcome to OpenPublic');
      $block['content'] = openpublic_splash_block_site_welcome();
      break;
    case 'site_config':
      $block['subject'] = t('Get Started');
      $block['content'] = openpublic_splash_block_site_config();
      break;
  }
  return $block;
}

/**
 * Loader function for hook_menu().
 */
function openpublic_splash_block_load($delta) {
  return block_load('openpublic_splash', $delta);
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function openpublic_splash_block_site_welcome() {
  $markup = '';
  $markup .= '<p>' . t('Ready to create a Drupal site?') . '</p>';
  $markup .= '<p>' . t('To get started with your site, go straight to the !dashboard. From there, you\'ll be able to choose your theme, personalize your site, and configure all the bells and whistles.', array('!dashboard' => l(t('Dashboard'), 'admin/dashboard', array('attributes' => array('class' => array('openpublic-splash-link')))))) . '</p>';
  $markup .= '<p>' . t('Tell us what you think, or better yet, !contribute to make it even better. Be The People!', array('!contribute' => l(t('contribute to OpenPublic'), 'http://openpublicapp.com/'))) . '</p>';

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function openpublic_splash_block_site_config() {
  $items = array();

  $markup = '';

  $items[] = array(
    'title' => t('Watch an Introductory Video'),
    'href' => 'http://p2te.ch/openpublicvideo',
    'localized_options' => array('attributes' => array('class' => array('openpublicvideo'))),
    'description' => t('New to OpenPublic? Take a video tour through the features and learn the basics before you get started.'),
  );

  $items[] = array(
    'title' => t('Change or Add a New Design'),
    'href' => 'admin/appearance',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-design'))),
    'description' => t('Switch easily to any of OpenPublic\'s preloaded themes, or add a new one of your own to customize your site\'s design.'),
  );

  $items[] = array(
    'title' => t('Configure Contexts, Layouts and Blocks'),
    'href' => 'admin/structure/context',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-context'))),
    'description' => t('Configure various contexts (sections) of your website, layouts used in those contexts and block placement in each context.'),
  );

  $items[] = array(
    'title' => t('Enter Content'),
    'href' => 'node/add',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),
    'description' => t('Start entering articles, blogs, photos, and other content. You can also remove demo content.'),
  );

  $items[] = array(
    'title' => t('Toggle demo content.'),
    'href' => 'admin/content/demo-toggle',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-demo-content'))),
    'description' => t('Demo content pre-loads sample content to show examples of the content types and features in this distribution.'),
  );



  $items[] = array(
    'title' => t('Personalize Site Settings'),
    'href' => 'admin/config/system/site-information',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-site-settings'))),
    'description' => t('Change the title, slogan, contact information, and default frontpage settings here.'),
  );

  $items[] = array(
    'title' => t('Manage User Roles'),
    'href' => 'admin/people/permissions/roles',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-roles'))),
    'description' => t('Set up roles for your users, contributors, and site administrators.'),
  );

  $items[] = array(
    'title' => t('Set User Permissions'),
    'href' => 'admin/people/permissions',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-permissions'))),
    'description' => t('Fine tune the permissions for each of your site\'s roles.'),
  );

  $content = array('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}


/**
 * Implements hook_block_display().
 */
function openpublic_splash_block_display($block) {
  $GLOBALS['devel_shutdown'] = FALSE; // Prevent devel module from spewing.
  $renderable_block = _block_get_renderable_array(_block_render_blocks(array($block)));
  print render($renderable_block);

  exit;
}

/**
 * Helper function to determine if all the tasks related to initial site configuration
 * have either been completed or dismissed.
 * TODO: Create a checklist of completed/dismissed tasks.
 * TODO: Check that list here.
 */
function openpublic_splash_site_welcome_check() {
  return TRUE;
}

/**
 * Returns map of demo app to parent app.
 */
function openpublic_splash_demo_modules() {
  if ($modules_cache = cache_get(__FUNCTION__)) {
    return $modules_cache->data;
  }
  elseif (function_exists('apps_include')) {
    $modules = array();
    apps_include('manifest');
    foreach (apps_apps('openpublic') as $app) {
      if (!empty($app['demo content module'])) {
        $modules[$app['demo content module']] = $app['machine_name'];
      }
    }
    cache_set(__FUNCTION__, $modules);
    return $modules;
  }
}

/**
 * Menu callback function to help toggle the demo content module's status.
 */
function openpublic_splash_toggle_demo_content() {
  $demo_modules = openpublic_splash_demo_modules();

  // If no demo modules enabled, enable them.
  if (!array_filter(array_keys($demo_modules), 'module_exists')) {
    module_enable(array_keys(array_filter($demo_modules, 'module_exists')));
    drupal_set_message(t('Demo content has been enabled.'));
  }
  else {
    module_disable(array_keys($demo_modules));
    drupal_set_message(t('Demo content has been disabled. <a href="@url">Reenable demo content</a>', array('@url' => url('admin/content/demo-toggle'))));

  }
  drupal_goto('admin/dashboard');
}
