<?php

// $Id$

/**
 * hook_menu - register a callback for 404 substitution
 */
function static_404_menu() {
  $menu = array();
  $menu['static_404'] = array(
    'title' => 'View static 404 page',
    'page callback' => 'static_404_return',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $menu;
}

/**
 * hook_form_FORM_ID_alter
 */
function static_404_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['error_page']['static_404'] = $form['error_page']['site_404'];
  $form['error_page']['static_404']['#default_value'] = variable_get('static_404', '');
  $form['error_page']['site_404']['#type'] = 'hidden';
  $form['error_page']['site_404']['#default_value'] = 'static_404';
  $form['error_page']['generate'] = array(
   '#type' => 'button',
   '#value' => t('Generate 404 Page'),
   '#name' => 'generate',
   '#executes_submit_callback' => TRUE,
  );
  array_unshift($form['#submit'], 'static_404_generate_submit');
}

/**
 * Submit callback for the site_information form which writes the 404 page.
 */
function static_404_generate_submit($form_id, $form_values) {
  if (!empty($form_values['input']['generate'])) {
    // Generate the page
    static_404_generate();

    // Redirect to the same page we're on
    if($form_values['input']['static_404'] === '') {
      drupal_set_message(t("Creating a default 404 page since you haven't "
        . "specified a Drupal page for me to copy. Provide a value for the "
        . "default 404 page for a custom static 404."), 'warning');
    } else {
      drupal_set_message(t('The 404 page has been created'), 'status');
    }
    drupal_goto('admin/config/system/site-information');
  }
}

function _static_404_make_404_dir() {
  if (!file_exists('public://404')) {
      drupal_mkdir('public://404', 0777);
  }
}
/**
 * if a static 404 exists, include it and exit
 */
function static_404_return() {
  if (file_exists('public://404/index.php')) {
    include_once 'public://404/index.php';
    drupal_exit();
  }
  else {
    return 'Not Found';
  }
}

/**
 * generate the real 404 page and save it statically.
 */
function static_404_generate() {
  global $base_url;
  $path = drupal_get_normal_path(variable_get('static_404', ''));
  if ($path) {
    $result = drupal_http_request($base_url . '/' . $path, array('timeout' => 10));
    if (!empty($result)) {
      if ($result->code == 200 && !empty($result->data)) {
        _static_404_make_404_dir();
        $directory = 'public://404';

        file_save_data($result->data, $directory . '/index.php', FILE_EXISTS_REPLACE);
        drupal_chmod($directory . '/index.php', 0777);
      }
    }
  }                                                
}
