<?php
/**
 * @file
 * openpublic_services_demo.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openpublic_services_demo_content_defaults() {
  $content = array();

  $content['services_disaster_response_assistance'] = (object) array(
    'exported_path' => 'service/disaster-response-assistance',
    'title' => 'Disaster Response Assistance',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'services',
    'language' => 'und',
    'created' => 1296153087,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'services_disaster_response_assistance',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Processus lobortis mazim littera decima eum. Ea laoreet laoreet et dignissim notare. Vulputate littera suscipit nobis exerci placerat. Eodem quis litterarum lius anteposuerit est. Littera elit ut in est imperdiet. Littera iis claritatem facit minim formas. Dignissim accumsan lius etiam tempor lius. 

Imperdiet littera quod dolor quam typi. Legentis minim hendrerit sollemnes augue luptatum. Lectores doming ii dolor liber vulputate. Parum mirum doming blandit dolor nam. Formas decima hendrerit minim littera ullamcorper. Consequat quarta nulla praesent magna esse. Dignissim videntur aliquam sit duis eorum. 

Sit non iriure claram augue velit. Iusto qui in eorum decima eorum. Eodem doming futurum minim blandit consuetudium. Facer hendrerit consequat me ad vel. Dignissim velit typi nobis gothica option. Eu nibh ipsum Investigationes quinta qui. Congue dolor adipiscing demonstraverunt quis tempor. 

Nisl in veniam dynamicus cum tincidunt. Dignissim veniam claritas processus quinta nonummy. Quod habent ut erat lius videntur. Nihil sollemnes aliquam feugiat claritatem ex.',
          'summary' => 'Processus lobortis mazim littera decima eum. Ea laoreet laoreet et dignissim notare. Vulputate littera suscipit nobis exerci placerat. Eodem quis litterarum lius anteposuerit est.',
          'format' => 'filtered_html',
          'safe_value' => '<p>Processus lobortis mazim littera decima eum. Ea laoreet laoreet et dignissim notare. Vulputate littera suscipit nobis exerci placerat. Eodem quis litterarum lius anteposuerit est. Littera elit ut in est imperdiet. Littera iis claritatem facit minim formas. Dignissim accumsan lius etiam tempor lius. </p>
<p>Imperdiet littera quod dolor quam typi. Legentis minim hendrerit sollemnes augue luptatum. Lectores doming ii dolor liber vulputate. Parum mirum doming blandit dolor nam. Formas decima hendrerit minim littera ullamcorper. Consequat quarta nulla praesent magna esse. Dignissim videntur aliquam sit duis eorum. </p>
<p>Sit non iriure claram augue velit. Iusto qui in eorum decima eorum. Eodem doming futurum minim blandit consuetudium. Facer hendrerit consequat me ad vel. Dignissim velit typi nobis gothica option. Eu nibh ipsum Investigationes quinta qui. Congue dolor adipiscing demonstraverunt quis tempor. </p>
<p>Nisl in veniam dynamicus cum tincidunt. Dignissim veniam claritas processus quinta nonummy. Quod habent ut erat lius videntur. Nihil sollemnes aliquam feugiat claritatem ex.</p>
',
          'safe_summary' => '<p>Processus lobortis mazim littera decima eum. Ea laoreet laoreet et dignissim notare. Vulputate littera suscipit nobis exerci placerat. Eodem quis litterarum lius anteposuerit est.</p>
',
        ),
      ),
    ),
    'field_services_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'services1.jpg',
          'uri' => 'public://services1.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 22998,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 300,
          'height' => 223,
        ),
      ),
    ),
  );

  $content['services_going_green_tax_credits'] = (object) array(
    'exported_path' => 'service/going-green-tax-credits',
    'title' => 'Going Green Tax Credits',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'services',
    'language' => 'und',
    'created' => 1296150984,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'services_going_green_tax_credits',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Per in liber erat id id. Quam facer consequat duis cum insitam. Vero elit eu magna facit ii. Adipiscing etiam wisi et processus notare. Hendrerit tincidunt non augue dolore quarta. Dolor est dynamicus elit usus liber. Qui facilisis dynamicus qui congue enim. Notare lectores insitam decima duis legentis. Est adipiscing lobortis nonummy ex illum. Saepius placerat facit lectorum est claram. Iriure qui illum feugiat magna liber. Consequat et est nulla liber consequat. Imperdiet quam legunt imperdiet formas consequat. Nunc quarta minim ea assum vel. 

Nisl formas parum legere claritatem lectorum. Possim consequat assum diam et nobis. Et commodo minim iis laoreet feugiat. Nunc commodo te claritatem quod legere. Nulla mutationem commodo facer luptatum vulputate. Modo placerat facilisis volutpat ullamcorper autem. Id iriure elit nobis fiant eleifend. Ullamcorper me nisl nunc congue typi. Iis placerat sit videntur in lectorum. Odio usus consectetuer ut parum facilisis. Tempor augue qui eorum consectetuer saepius. Eodem aliquam nisl vero assum parum. Doming liber parum duis usus eros. Nonummy magna aliquam eros sed videntur. 

Molestie id quod option insitam vel. Decima futurum ut molestie congue littera. Vel qui consequat eodem ii praesent. Seacula sequitur vulputate nam zzril duis. Littera congue lobortis in erat claritatem. Eros iusto illum lorem typi enim. Euismod Investigationes quam hendrerit eu nobis. ',
          'summary' => 'Per in liber erat id id. Quam facer consequat duis cum insitam. Vero elit eu magna facit ii. Adipiscing etiam wisi et processus notare. Hendrerit tincidunt non augue dolore quarta. Dolor est dynamicus elit usus liber. Qui facilisis dynamicus qui congue enim. Notare lectores insitam decima duis legentis.',
          'format' => 'filtered_html',
          'safe_value' => '<p>Per in liber erat id id. Quam facer consequat duis cum insitam. Vero elit eu magna facit ii. Adipiscing etiam wisi et processus notare. Hendrerit tincidunt non augue dolore quarta. Dolor est dynamicus elit usus liber. Qui facilisis dynamicus qui congue enim. Notare lectores insitam decima duis legentis. Est adipiscing lobortis nonummy ex illum. Saepius placerat facit lectorum est claram. Iriure qui illum feugiat magna liber. Consequat et est nulla liber consequat. Imperdiet quam legunt imperdiet formas consequat. Nunc quarta minim ea assum vel. </p>
<p>Nisl formas parum legere claritatem lectorum. Possim consequat assum diam et nobis. Et commodo minim iis laoreet feugiat. Nunc commodo te claritatem quod legere. Nulla mutationem commodo facer luptatum vulputate. Modo placerat facilisis volutpat ullamcorper autem. Id iriure elit nobis fiant eleifend. Ullamcorper me nisl nunc congue typi. Iis placerat sit videntur in lectorum. Odio usus consectetuer ut parum facilisis. Tempor augue qui eorum consectetuer saepius. Eodem aliquam nisl vero assum parum. Doming liber parum duis usus eros. Nonummy magna aliquam eros sed videntur. </p>
<p>Molestie id quod option insitam vel. Decima futurum ut molestie congue littera. Vel qui consequat eodem ii praesent. Seacula sequitur vulputate nam zzril duis. Littera congue lobortis in erat claritatem. Eros iusto illum lorem typi enim. Euismod Investigationes quam hendrerit eu nobis.</p>
',
          'safe_summary' => '<p>Per in liber erat id id. Quam facer consequat duis cum insitam. Vero elit eu magna facit ii. Adipiscing etiam wisi et processus notare. Hendrerit tincidunt non augue dolore quarta. Dolor est dynamicus elit usus liber. Qui facilisis dynamicus qui congue enim. Notare lectores insitam decima duis legentis.</p>
',
        ),
      ),
    ),
    'field_services_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'photo130x80v3.jpg',
          'uri' => 'public://photo130x80v3.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 9401,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 130,
          'height' => 80,
        ),
      ),
    ),
  );

  $content['services_grant_opportunities'] = (object) array(
    'exported_path' => 'service/grant-opportunities',
    'title' => 'Grant Opportunities',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'services',
    'language' => 'und',
    'created' => 1296149164,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'services_grant_opportunities',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Illum sed tation nulla est sequitur. Praesent typi lobortis decima consequat duis. Liber diam nonummy eleifend esse possim. Augue nunc doming euismod nostrud hendrerit. Diam volutpat seacula et lius lorem. In quinta iusto claram et ut. Dolor etiam erat hendrerit vulputate parum. Euismod delenit veniam fiant usus etiam. Esse facit formas usus decima insitam. Accumsan tempor soluta accumsan et parum. Dolor aliquam nonummy etiam legentis in. Claritas typi hendrerit aliquam erat tation. Delenit wisi qui eorum amet feugiat. Decima lobortis et nobis blandit imperdiet. 

Vulputate tation quis ut sequitur me. Tempor blandit option mazim feugiat amet. Duis habent et putamus luptatum amet. Facilisi claram nulla humanitatis vel nobis. Decima delenit in te nonummy claritas. Wisi usus saepius cum demonstraverunt accumsan. Lobortis claritas consequat amet formas congue. Mutationem mutationem placerat qui iriure putamus. In lorem est dolor magna volutpat. Vero suscipit soluta formas qui consequat. Ut anteposuerit ut notare vero iis. Lorem ut congue zzril quarta molestie. Aliquip mazim decima putamus me sit. Suscipit aliquam option augue ullamcorper zzril. 

Quam sed elit nunc qui ut. Vero mirum usus claritatem consequat nunc. Vel enim aliquip litterarum gothica qui. Legentis congue consequat delenit in dolore. Legunt nonummy elit parum formas typi. Feugait nostrud duis te in luptatum. Typi nostrud assum in mirum suscipit. Clari legunt qui me magna tation. Qui insitam in delenit parum lobortis. Clari notare quarta blandit dolore tincidunt. Vero futurum euismod insitam iis habent. Velit facit aliquip claram dynamicus ii. Magna doming duis notare eleifend claritas. ',
          'summary' => 'Illum sed tation nulla est sequitur. Praesent typi lobortis decima consequat duis. Liber diam nonummy eleifend esse possim. Augue nunc doming euismod nostrud hendrerit. Diam volutpat seacula et lius lorem. In quinta iusto claram et ut. Dolor etiam erat hendrerit vulputate parum.',
          'format' => 'filtered_html',
          'safe_value' => '<p>Illum sed tation nulla est sequitur. Praesent typi lobortis decima consequat duis. Liber diam nonummy eleifend esse possim. Augue nunc doming euismod nostrud hendrerit. Diam volutpat seacula et lius lorem. In quinta iusto claram et ut. Dolor etiam erat hendrerit vulputate parum. Euismod delenit veniam fiant usus etiam. Esse facit formas usus decima insitam. Accumsan tempor soluta accumsan et parum. Dolor aliquam nonummy etiam legentis in. Claritas typi hendrerit aliquam erat tation. Delenit wisi qui eorum amet feugiat. Decima lobortis et nobis blandit imperdiet. </p>
<p>Vulputate tation quis ut sequitur me. Tempor blandit option mazim feugiat amet. Duis habent et putamus luptatum amet. Facilisi claram nulla humanitatis vel nobis. Decima delenit in te nonummy claritas. Wisi usus saepius cum demonstraverunt accumsan. Lobortis claritas consequat amet formas congue. Mutationem mutationem placerat qui iriure putamus. In lorem est dolor magna volutpat. Vero suscipit soluta formas qui consequat. Ut anteposuerit ut notare vero iis. Lorem ut congue zzril quarta molestie. Aliquip mazim decima putamus me sit. Suscipit aliquam option augue ullamcorper zzril. </p>
<p>Quam sed elit nunc qui ut. Vero mirum usus claritatem consequat nunc. Vel enim aliquip litterarum gothica qui. Legentis congue consequat delenit in dolore. Legunt nonummy elit parum formas typi. Feugait nostrud duis te in luptatum. Typi nostrud assum in mirum suscipit. Clari legunt qui me magna tation. Qui insitam in delenit parum lobortis. Clari notare quarta blandit dolore tincidunt. Vero futurum euismod insitam iis habent. Velit facit aliquip claram dynamicus ii. Magna doming duis notare eleifend claritas.</p>
',
          'safe_summary' => '<p>Illum sed tation nulla est sequitur. Praesent typi lobortis decima consequat duis. Liber diam nonummy eleifend esse possim. Augue nunc doming euismod nostrud hendrerit. Diam volutpat seacula et lius lorem. In quinta iusto claram et ut. Dolor etiam erat hendrerit vulputate parum.</p>
',
        ),
      ),
    ),
    'field_services_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'grant.jpg',
          'uri' => 'public://grant.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 76967,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 426,
          'height' => 426,
        ),
      ),
    ),
  );

  $content['services_learning_programs'] = (object) array(
    'exported_path' => 'service/learning-programs',
    'title' => 'Learning Programs',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'services',
    'language' => 'und',
    'created' => 1296151046,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'services_learning_programs',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Eros in claram iusto gothica demonstraverunt. Dolore ipsum facilisi modo assum non. Eum parum nulla ut commodo demonstraverunt. At ipsum notare nostrud placerat aliquip. Mazim facit aliquam liber quarta quod. Claritatem lius placerat et laoreet claritas. Facilisi eodem claram blandit saepius decima. Blandit quinta illum usus minim modo. Eu quarta anteposuerit sit amet ex. Claritatem mutationem formas enim clari soluta. Legunt mazim adipiscing liber dolore parum. Euismod velit saepius etiam dolor qui. Sed blandit liber vulputate per laoreet. Non demonstraverunt usus nulla legunt hendrerit. 

Humanitatis id qui quinta erat legunt. Eleifend facer blandit claritatem imperdiet dolore. Decima decima ea praesent ad dynamicus. Futurum gothica qui nonummy etiam sequitur. Iis parum usus te decima parum. Dolore odio nunc eu vero nostrud. Quod fiant est dolor accumsan per. 

Quis ut clari putamus ut nihil. Gothica erat dolore eodem sit ea. Euismod tempor at consectetuer ut sit. Enim nulla elit parum legere eleifend. Eu duis facer duis decima odio. Option cum imperdiet consectetuer sollemnes eum. Id option decima ex non duis. Facilisi possim assum magna eodem lectorum. Sequitur sollemnes nunc tincidunt in nunc. Qui claritas amet esse zzril soluta. Minim liber nunc nobis accumsan placerat. Nibh dolor erat dolore quod sit. In nibh typi sollemnes in dolore. Nam iusto quod consectetuer facit option. Lectorum eum iriure consequat dignissim eorum. Duis vero littera et id est. Non dolor ut non humanitatis quod.',
          'summary' => 'Ros in claram iusto gothica demonstraverunt. Dolore ipsum facilisi modo assum non. Eum parum nulla ut commodo demonstraverunt. At ipsum notare nostrud placerat aliquip. ',
          'format' => 'filtered_html',
          'safe_value' => '<p>Eros in claram iusto gothica demonstraverunt. Dolore ipsum facilisi modo assum non. Eum parum nulla ut commodo demonstraverunt. At ipsum notare nostrud placerat aliquip. Mazim facit aliquam liber quarta quod. Claritatem lius placerat et laoreet claritas. Facilisi eodem claram blandit saepius decima. Blandit quinta illum usus minim modo. Eu quarta anteposuerit sit amet ex. Claritatem mutationem formas enim clari soluta. Legunt mazim adipiscing liber dolore parum. Euismod velit saepius etiam dolor qui. Sed blandit liber vulputate per laoreet. Non demonstraverunt usus nulla legunt hendrerit. </p>
<p>Humanitatis id qui quinta erat legunt. Eleifend facer blandit claritatem imperdiet dolore. Decima decima ea praesent ad dynamicus. Futurum gothica qui nonummy etiam sequitur. Iis parum usus te decima parum. Dolore odio nunc eu vero nostrud. Quod fiant est dolor accumsan per. </p>
<p>Quis ut clari putamus ut nihil. Gothica erat dolore eodem sit ea. Euismod tempor at consectetuer ut sit. Enim nulla elit parum legere eleifend. Eu duis facer duis decima odio. Option cum imperdiet consectetuer sollemnes eum. Id option decima ex non duis. Facilisi possim assum magna eodem lectorum. Sequitur sollemnes nunc tincidunt in nunc. Qui claritas amet esse zzril soluta. Minim liber nunc nobis accumsan placerat. Nibh dolor erat dolore quod sit. In nibh typi sollemnes in dolore. Nam iusto quod consectetuer facit option. Lectorum eum iriure consequat dignissim eorum. Duis vero littera et id est. Non dolor ut non humanitatis quod.</p>
',
          'safe_summary' => '<p>Ros in claram iusto gothica demonstraverunt. Dolore ipsum facilisi modo assum non. Eum parum nulla ut commodo demonstraverunt. At ipsum notare nostrud placerat aliquip.</p>
',
        ),
      ),
    ),
    'field_services_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'edu.jpg',
          'uri' => 'public://edu.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 6820,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 130,
          'height' => 80,
        ),
      ),
    ),
  );

  $content['services_research_assistance'] = (object) array(
    'exported_path' => 'service/research-assistance',
    'title' => 'Research Assistance',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'services',
    'language' => 'und',
    'created' => 1296150874,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'services_research_assistance',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Mirum nostrud velit feugait duis fiant. Decima consequat saepius iusto littera claram. Quarta mutationem eleifend littera sed augue. Nihil imperdiet legere cum iusto aliquip. Illum et eleifend eleifend euismod sed. Duis sed lectorum ullamcorper lius claritas. Iriure assum gothica saepius cum consuetudium. 

Fiant iriure sed vel velit non. Tincidunt minim praesent ii odio ii. Iis et tempor in congue eorum. Futurum tation quinta mirum dolore feugiat. Iusto exerci seacula typi mirum processus. Vel amet praesent claritas nunc est. Laoreet videntur sit processus enim aliquip. 

Eodem id ullamcorper iusto putamus et. Et laoreet vulputate soluta et facilisi. Nibh quod nulla mazim lectorum diam. Exerci soluta ea nibh saepius notare. Wisi Investigationes augue velit habent nulla. Iusto claritatem nisl facilisi nam saepius. Lectores laoreet velit iriure claritatem odio.',
          'summary' => 'Fiant iriure sed vel velit non. Tincidunt minim praesent ii odio ii. Iis et tempor in congue eorum. Futurum tation quinta mirum dolore feugiat. Iusto exerci seacula typi mirum processus.',
          'format' => 'filtered_html',
          'safe_value' => '<p>Mirum nostrud velit feugait duis fiant. Decima consequat saepius iusto littera claram. Quarta mutationem eleifend littera sed augue. Nihil imperdiet legere cum iusto aliquip. Illum et eleifend eleifend euismod sed. Duis sed lectorum ullamcorper lius claritas. Iriure assum gothica saepius cum consuetudium. </p>
<p>Fiant iriure sed vel velit non. Tincidunt minim praesent ii odio ii. Iis et tempor in congue eorum. Futurum tation quinta mirum dolore feugiat. Iusto exerci seacula typi mirum processus. Vel amet praesent claritas nunc est. Laoreet videntur sit processus enim aliquip. </p>
<p>Eodem id ullamcorper iusto putamus et. Et laoreet vulputate soluta et facilisi. Nibh quod nulla mazim lectorum diam. Exerci soluta ea nibh saepius notare. Wisi Investigationes augue velit habent nulla. Iusto claritatem nisl facilisi nam saepius. Lectores laoreet velit iriure claritatem odio.</p>
',
          'safe_summary' => '<p>Fiant iriure sed vel velit non. Tincidunt minim praesent ii odio ii. Iis et tempor in congue eorum. Futurum tation quinta mirum dolore feugiat. Iusto exerci seacula typi mirum processus.</p>
',
        ),
      ),
    ),
    'field_services_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'research.jpg',
          'uri' => 'public://research.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 144662,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 443,
          'height' => 443,
        ),
      ),
    ),
  );

return $content;
}
