<?php
/**
 * @file
 * openpublic_multimedia.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function openpublic_multimedia_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_media_gallery_media'
  $field_bases['field_media_gallery_media'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_media_gallery_media',
    'foreign keys' => array(
      'nid' => array(
        'columns' => array(
          'nid' => 'nid',
        ),
        'table' => 'node',
      ),
    ),
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'blog_entry' => 0,
        'document' => 0,
        'editors_choice' => 0,
        'event' => 0,
        'faqs' => 0,
        'home_page_feature' => 0,
        'media_gallery' => 0,
        'photo' => 'photo',
        'press_release' => 0,
        'profile' => 0,
        'resource' => 0,
        'services' => 0,
        'site_page' => 0,
        'webform' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 1,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_photo_image'
  $field_bases['field_photo_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_photo_image',
    'foreign keys' => array(
      'fid' => array(
        'columns' => array(
          'fid' => 'fid',
        ),
        'table' => 'file_managed',
      ),
    ),
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 1,
    'type' => 'image',
  );

  return $field_bases;
}
