<?php
/**
 * @file
 * Define plugin and activate.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function context_condition_admin_theme_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function context_condition_admin_theme_context_plugins() {
  $plugins = array();
  $plugins['context_condition_admin_theme'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_condition_admin_theme') . '/plugins',
      'file' => 'context_condition_admin_theme.inc',
      'class' => 'context_condition_admin_theme',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}


/**
 * Implements hook_context_registry().
 */
function context_condition_admin_theme_context_registry() {
  $registry = array();

  $registry['conditions'] = array(
    'admin_theme' => array(
      'title' => t('Admin Theme'),
      'description' => 'Set this context on the basis if the Admin theme is in use',
      'plugin' => 'context_condition_admin_theme',
    ),
  );

  return $registry;
}

/**
 * Implements hook_context_page_reaction().
 *
 * Adds context based on the browser keywords string.
 */
function context_condition_admin_theme_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'admin_theme')) {
    $plugin->execute();
  }
}
