<?php
/**
 * @file
 * openpublic_person_demo.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openpublic_person_demo_content_defaults() {
  $content = array();

  $content['abraham_lincoln'] = (object) array(
    'exported_path' => 'profile/abraham-lincoln',
    'title' => 'Abraham Lincoln',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1297110068,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'abraham_lincoln',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Id consequat mazim feugiat possim liber. Dolore diam option in nulla euismod. Parum liber qui nobis vero placerat. Nonummy legunt qui diam fiant facer. Duis molestie dolore liber claritatem est. In eu claritas assum dolore decima. Putamus velit hendrerit dolore commodo in. Consuetudium esse congue typi consequat Investigationes. Augue nonummy quam typi mazim litterarum. Lius consectetuer littera usus legunt odio. Sollemnes decima quod sollemnes delenit placerat. Quod usus enim dolore eum magna. Placerat assum lius lorem vel exerci. Usus eleifend volutpat lectorum odio soluta. 

Et videntur ut nisl lorem aliquip. Soluta insitam eleifend dignissim vel in. Vel erat soluta me accumsan tempor. Nunc consequat nulla mirum duis parum. Doming in putamus wisi quod tation. Mazim qui facer elit duis vulputate. Esse nulla anteposuerit me quod et. Et dignissim ut quod gothica enim. Nunc dolor dolore consuetudium eorum veniam. Erat zzril consuetudium etiam quarta nisl. Eros parum consuetudium nonummy congue duis. Consectetuer eros duis per augue habent. Consuetudium velit elit vel feugiat est. Seacula velit non vero nunc mutationem. ',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Id consequat mazim feugiat possim liber. Dolore diam option in nulla euismod. Parum liber qui nobis vero placerat. Nonummy legunt qui diam fiant facer. Duis molestie dolore liber claritatem est. In eu claritas assum dolore decima. Putamus velit hendrerit dolore commodo in. Consuetudium esse congue typi consequat Investigationes. Augue nonummy quam typi mazim litterarum. Lius consectetuer littera usus legunt odio. Sollemnes decima quod sollemnes delenit placerat. Quod usus enim dolore eum magna. Placerat assum lius lorem vel exerci. Usus eleifend volutpat lectorum odio soluta. </p>
<p>Et videntur ut nisl lorem aliquip. Soluta insitam eleifend dignissim vel in. Vel erat soluta me accumsan tempor. Nunc consequat nulla mirum duis parum. Doming in putamus wisi quod tation. Mazim qui facer elit duis vulputate. Esse nulla anteposuerit me quod et. Et dignissim ut quod gothica enim. Nunc dolor dolore consuetudium eorum veniam. Erat zzril consuetudium etiam quarta nisl. Eros parum consuetudium nonummy congue duis. Consectetuer eros duis per augue habent. Consuetudium velit elit vel feugiat est. Seacula velit non vero nunc mutationem.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Abraham',
          'format' => NULL,
          'safe_value' => 'Abraham',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Former President of the United States',
          'format' => NULL,
          'safe_value' => 'Former President of the United States',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Lincoln',
          'format' => NULL,
          'safe_value' => 'Lincoln',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'abe_lincoln.jpeg',
          'uri' => 'public://abe_lincoln.jpeg',
          'filemime' => 'image/jpeg',
          'filesize' => 2947,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 107,
          'height' => 143,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['alexander_johnson_johnson_default_content'] = (object) array(
    'exported_path' => 'profile/alexander-johnson',
    'title' => 'Alexander Johnson',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1293659808,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'alexander_johnson_johnson_default_content',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Sequitur littera habent vel esse nonummy. Praesent quis id parum vulputate velit. Qui in qui at amet accumsan. Demonstraverunt decima est nobis imperdiet eodem. Littera quinta quarta wisi quam in. Quis minim nobis elit exerci consuetudium. Soluta et facer nunc lectorum congue. 

Dolore typi saepius etiam nibh wisi. Id dolore sollemnes quod qui doming. Duis sollemnes sed molestie facilisis accumsan. Quinta ut exerci in lobortis quod. Anteposuerit nulla per vel mirum mirum. Amet augue eodem ut legere enim. Lobortis nonummy dolore qui mazim molestie. 

Saepius notare futurum et iis in. Qui humanitatis facilisis consequat eleifend doming. Congue facit dolore eu tation praesent. Clari assum mutationem quam legere accumsan. Assum legentis quod enim lectores mazim. Qui facit autem ea nam feugait. Ut legentis cum nostrud diam nulla. 

Iusto non facer nibh lectores dolor. Luptatum eros putamus odio qui doming. Nunc lorem littera modo lobortis nulla. Consuetudium claritatem habent vero suscipit sed. Liber quam nunc eu feugiat velit. Luptatum feugait dolore at typi duis. Insitam insitam insitam putamus humanitatis facilisis. 

Saepius modo legere per consequat ad. Option parum consequat blandit eu zzril. Lobortis lobortis eorum veniam et nobis. Dolor mazim legunt ut nostrud dignissim. Claritatem consectetuer insitam mazim clari nunc. Eros eum fiant facilisis nulla habent. Claritatem soluta ad esse luptatum elit. 

Qui videntur nunc enim suscipit iusto. Lectores eu demonstraverunt claritas et et. Sollemnes legunt volutpat demonstraverunt quinta aliquam. Dignissim tation ullamcorper facilisi augue nostrud. Soluta enim enim in modo dynamicus. Nunc nulla est parum per anteposuerit. Per elit qui assum aliquip lectorum. 

Futurum sequitur legunt odio anteposuerit quod. Non et feugait euismod demonstraverunt lorem. Dolor dynamicus decima anteposuerit blandit sit. Ipsum futurum dolore facilisis luptatum futurum. Esse quod iusto nunc amet cum. Investigationes sollemnes quarta mutationem ad dignissim. Imperdiet duis liber qui eodem dolore. 

Minim claritatem option wisi legunt minim. Iis nunc nunc demonstraverunt ut decima.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Sequitur littera habent vel esse nonummy. Praesent quis id parum vulputate velit. Qui in qui at amet accumsan. Demonstraverunt decima est nobis imperdiet eodem. Littera quinta quarta wisi quam in. Quis minim nobis elit exerci consuetudium. Soluta et facer nunc lectorum congue. </p>
<p>Dolore typi saepius etiam nibh wisi. Id dolore sollemnes quod qui doming. Duis sollemnes sed molestie facilisis accumsan. Quinta ut exerci in lobortis quod. Anteposuerit nulla per vel mirum mirum. Amet augue eodem ut legere enim. Lobortis nonummy dolore qui mazim molestie. </p>
<p>Saepius notare futurum et iis in. Qui humanitatis facilisis consequat eleifend doming. Congue facit dolore eu tation praesent. Clari assum mutationem quam legere accumsan. Assum legentis quod enim lectores mazim. Qui facit autem ea nam feugait. Ut legentis cum nostrud diam nulla. </p>
<p>Iusto non facer nibh lectores dolor. Luptatum eros putamus odio qui doming. Nunc lorem littera modo lobortis nulla. Consuetudium claritatem habent vero suscipit sed. Liber quam nunc eu feugiat velit. Luptatum feugait dolore at typi duis. Insitam insitam insitam putamus humanitatis facilisis. </p>
<p>Saepius modo legere per consequat ad. Option parum consequat blandit eu zzril. Lobortis lobortis eorum veniam et nobis. Dolor mazim legunt ut nostrud dignissim. Claritatem consectetuer insitam mazim clari nunc. Eros eum fiant facilisis nulla habent. Claritatem soluta ad esse luptatum elit. </p>
<p>Qui videntur nunc enim suscipit iusto. Lectores eu demonstraverunt claritas et et. Sollemnes legunt volutpat demonstraverunt quinta aliquam. Dignissim tation ullamcorper facilisi augue nostrud. Soluta enim enim in modo dynamicus. Nunc nulla est parum per anteposuerit. Per elit qui assum aliquip lectorum. </p>
<p>Futurum sequitur legunt odio anteposuerit quod. Non et feugait euismod demonstraverunt lorem. Dolor dynamicus decima anteposuerit blandit sit. Ipsum futurum dolore facilisis luptatum futurum. Esse quod iusto nunc amet cum. Investigationes sollemnes quarta mutationem ad dignissim. Imperdiet duis liber qui eodem dolore. </p>
<p>Minim claritatem option wisi legunt minim. Iis nunc nunc demonstraverunt ut decima.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_department' => array(
      'und' => array(
        0 => array(
          'value' => 'Department of Energy',
          'format' => NULL,
          'safe_value' => 'Department of Energy',
        ),
      ),
    ),
    'field_profile_email' => array(
      'und' => array(
        0 => array(
          'value' => 'ajohnson@example.gov',
          'format' => NULL,
          'safe_value' => 'ajohnson@example.gov',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Alexander',
          'format' => NULL,
          'safe_value' => 'Alexander',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Director of Energy',
          'format' => NULL,
          'safe_value' => 'Director of Energy',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Johnson',
          'format' => NULL,
          'safe_value' => 'Johnson',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
    'field_profile_phone' => array(
      'und' => array(
        0 => array(
          'value' => '543-342-5555',
          'format' => NULL,
          'safe_value' => '543-342-5555',
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'Everett_dirksen_painting.jpg (610×828)-1.jpg',
          'uri' => 'public://Everett_dirksen_painting.jpg (610×828)-1.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 16686,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 205,
          'height' => 271,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['david_brown_brown'] = (object) array(
    'exported_path' => 'profile/david-brown',
    'title' => 'David Brown',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1293659506,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'david_brown_brown',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Zzril lius delenit nibh videntur nulla. Illum ipsum nonummy elit vulputate nunc. Per quis facilisis wisi dolor ut. Imperdiet quinta mutationem dignissim ipsum quis. Quod suscipit etiam duis dynamicus et. Diam lorem anteposuerit quod vel qui. Enim at eleifend nostrud tempor notare. 

Eodem augue quarta lobortis volutpat imperdiet. Nulla lectores est etiam claritas quarta. Claritatem sed in eorum eu est. Veniam lobortis elit dolore ipsum litterarum. Velit qui sit facilisis facilisis fiant. Ad vulputate ut vel nulla fiant. Nobis vel claritatem lorem zzril in. 

Qui videntur ad zzril facilisis mutationem. Illum lectores placerat at iis nibh. Minim augue humanitatis typi at dolore. Vel nisl etiam commodo tempor consectetuer. Decima est ii formas legunt non. Ex dolore lectores id duis consequat. Enim nam option non ipsum est. 

Est eodem consectetuer accumsan et iriure. Veniam blandit laoreet sed ex sollemnes. In etiam luptatum et erat typi. Investigationes habent velit assum nunc ipsum. Esse per imperdiet nobis legere quod. Qui diam vel legunt dolore aliquip. Eum nisl nonummy eu elit ea. 

Minim tation parum notare nulla nobis. Insitam nulla claritatem processus quam autem. Usus modo ad saepius hendrerit possim. Exerci ut typi est quis claritatem. Delenit illum quinta dignissim eorum nunc. Quarta mirum iriure quam quam dolore. Nam quam cum legentis formas accumsan. 

Enim vulputate parum legentis id quinta. Imperdiet nobis decima usus qui putamus. Lectorum zzril aliquam vero euismod dignissim. Mutationem enim delenit ea euismod claram. Ex et aliquip wisi eu eodem. Legentis consequat cum videntur tempor eu. Delenit me consequat typi feugait exerci. 

Accumsan Investigationes legere enim nulla mutationem. Erat in saepius insitam gothica vel. Sit vulputate luptatum nibh accumsan consuetudium. In ut in nonummy congue cum. Facer consuetudium decima non legunt nibh. Dynamicus ipsum dolore quam dolore ex. Duis nobis sequitur nobis gothica claram. 

Est qui te velit legere decima.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Zzril lius delenit nibh videntur nulla. Illum ipsum nonummy elit vulputate nunc. Per quis facilisis wisi dolor ut. Imperdiet quinta mutationem dignissim ipsum quis. Quod suscipit etiam duis dynamicus et. Diam lorem anteposuerit quod vel qui. Enim at eleifend nostrud tempor notare. </p>
<p>Eodem augue quarta lobortis volutpat imperdiet. Nulla lectores est etiam claritas quarta. Claritatem sed in eorum eu est. Veniam lobortis elit dolore ipsum litterarum. Velit qui sit facilisis facilisis fiant. Ad vulputate ut vel nulla fiant. Nobis vel claritatem lorem zzril in. </p>
<p>Qui videntur ad zzril facilisis mutationem. Illum lectores placerat at iis nibh. Minim augue humanitatis typi at dolore. Vel nisl etiam commodo tempor consectetuer. Decima est ii formas legunt non. Ex dolore lectores id duis consequat. Enim nam option non ipsum est. </p>
<p>Est eodem consectetuer accumsan et iriure. Veniam blandit laoreet sed ex sollemnes. In etiam luptatum et erat typi. Investigationes habent velit assum nunc ipsum. Esse per imperdiet nobis legere quod. Qui diam vel legunt dolore aliquip. Eum nisl nonummy eu elit ea. </p>
<p>Minim tation parum notare nulla nobis. Insitam nulla claritatem processus quam autem. Usus modo ad saepius hendrerit possim. Exerci ut typi est quis claritatem. Delenit illum quinta dignissim eorum nunc. Quarta mirum iriure quam quam dolore. Nam quam cum legentis formas accumsan. </p>
<p>Enim vulputate parum legentis id quinta. Imperdiet nobis decima usus qui putamus. Lectorum zzril aliquam vero euismod dignissim. Mutationem enim delenit ea euismod claram. Ex et aliquip wisi eu eodem. Legentis consequat cum videntur tempor eu. Delenit me consequat typi feugait exerci. </p>
<p>Accumsan Investigationes legere enim nulla mutationem. Erat in saepius insitam gothica vel. Sit vulputate luptatum nibh accumsan consuetudium. In ut in nonummy congue cum. Facer consuetudium decima non legunt nibh. Dynamicus ipsum dolore quam dolore ex. Duis nobis sequitur nobis gothica claram. </p>
<p>Est qui te velit legere decima.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_department' => array(
      'und' => array(
        0 => array(
          'value' => 'Energy',
          'format' => NULL,
          'safe_value' => 'Energy',
        ),
      ),
    ),
    'field_profile_email' => array(
      'und' => array(
        0 => array(
          'value' => 'davidbrown@example.gov',
          'format' => NULL,
          'safe_value' => 'davidbrown@example.gov',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'David',
          'format' => NULL,
          'safe_value' => 'David',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Deputy Director of Energy',
          'format' => NULL,
          'safe_value' => 'Deputy Director of Energy',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Brown',
          'format' => NULL,
          'safe_value' => 'Brown',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 0,
        ),
      ),
    ),
    'field_profile_phone' => array(
      'und' => array(
        0 => array(
          'value' => '475-234-5555',
          'format' => NULL,
          'safe_value' => '475-234-5555',
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'garzon_valdes.jpg',
          'uri' => 'public://garzon_valdes.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 42008,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 152,
          'height' => 183,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['eric_smith'] = (object) array(
    'exported_path' => 'profile/eric-smith',
    'title' => 'Eric Smith',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1297110624,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'eric_smith',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Wisi cum possim claram sequitur claram. Parum assum imperdiet eu nulla et. Lorem commodo typi magna minim consequat. Ex ii etiam legunt blandit lius. Humanitatis in te in seacula typi. Id est parum dolore euismod ex. Quam formas in liber enim est. 

Dynamicus odio suscipit in clari in. Typi feugait nonummy qui possim anteposuerit. Litterarum iis claram typi iusto me. Velit humanitatis non seacula in enim. Cum nobis esse feugait id ullamcorper. Odio blandit facit dynamicus usus illum. Nihil claritatem euismod liber nobis litterarum. 

Eorum eorum per diam humanitatis eum. Exerci ut demonstraverunt elit anteposuerit quis. Est vero enim vel sequitur commodo. Dolore duis anteposuerit volutpat euismod iis. Amet aliquam ut mutationem imperdiet lius. Qui habent in praesent qui duis. Lorem commodo blandit zzril adipiscing ex. 

Velit quinta at eu legunt ut. Gothica nobis seacula ut est mutationem. Option qui consequat qui qui feugiat. Mirum iriure insitam duis aliquip cum. Aliquam modo typi quarta adipiscing lobortis. Te magna iis id imperdiet esse. Magna parum liber ullamcorper dignissim nibh. Suscipit quarta molestie consequat et veniam. In magna iis quinta qui wisi. Sit nonummy legere lius legentis magna.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Wisi cum possim claram sequitur claram. Parum assum imperdiet eu nulla et. Lorem commodo typi magna minim consequat. Ex ii etiam legunt blandit lius. Humanitatis in te in seacula typi. Id est parum dolore euismod ex. Quam formas in liber enim est. </p>
<p>Dynamicus odio suscipit in clari in. Typi feugait nonummy qui possim anteposuerit. Litterarum iis claram typi iusto me. Velit humanitatis non seacula in enim. Cum nobis esse feugait id ullamcorper. Odio blandit facit dynamicus usus illum. Nihil claritatem euismod liber nobis litterarum. </p>
<p>Eorum eorum per diam humanitatis eum. Exerci ut demonstraverunt elit anteposuerit quis. Est vero enim vel sequitur commodo. Dolore duis anteposuerit volutpat euismod iis. Amet aliquam ut mutationem imperdiet lius. Qui habent in praesent qui duis. Lorem commodo blandit zzril adipiscing ex. </p>
<p>Velit quinta at eu legunt ut. Gothica nobis seacula ut est mutationem. Option qui consequat qui qui feugiat. Mirum iriure insitam duis aliquip cum. Aliquam modo typi quarta adipiscing lobortis. Te magna iis id imperdiet esse. Magna parum liber ullamcorper dignissim nibh. Suscipit quarta molestie consequat et veniam. In magna iis quinta qui wisi. Sit nonummy legere lius legentis magna.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Eric',
          'format' => NULL,
          'safe_value' => 'Eric',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Financial Analyst',
          'format' => NULL,
          'safe_value' => 'Financial Analyst',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Smith',
          'format' => NULL,
          'safe_value' => 'Smith',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 0,
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'photo95x95-blank.jpg',
          'uri' => 'public://photo95x95-blank.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 1514,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 95,
          'height' => 95,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['lyndon_johnson'] = (object) array(
    'exported_path' => 'profile/lyndon-johnson',
    'title' => 'Lyndon Johnson',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1293658056,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'lyndon_johnson',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Ea nobis facilisi decima facilisis eum. Est typi quod nonummy littera non. Placerat quarta duis facer processus hendrerit. Volutpat legere legentis soluta putamus eum. Aliquam te seacula ex facilisis delenit. Exerci parum vero dolor zzril notare. In est lobortis legentis in tincidunt. 

In vel usus in dolor suscipit. Sequitur lectorum feugait veniam et quinta. Claritatem facilisis nobis velit in lius. Feugiat nobis iis processus cum blandit. Vulputate usus eu hendrerit ut est. Decima dynamicus ex accumsan dolor autem. Insitam typi molestie praesent ut eleifend. Typi suscipit ut blandit ipsum sequitur. Dolore dignissim tincidunt ut erat nibh. Possim veniam gothica legunt legere wisi. Consuetudium tincidunt odio decima magna quinta. Modo me in consectetuer nunc qui. Nulla soluta futurum nostrud sollemnes parum. Placerat non etiam futurum euismod qui. Aliquip zzril nulla ut claritatem parum. 

Lobortis lius parum vel wisi dolore. In exerci esse nulla nunc modo. Aliquip est videntur te typi nibh. Te dolor nam in imperdiet iis. Decima quarta diam facilisis et in. Iriure est iriure eros vero usus. Typi nulla ut enim quinta molestie. Zzril volutpat duis quinta nulla eros. Lectores non euismod delenit diam facilisis. Praesent parum typi at erat dolore. Legunt in typi dolore nulla clari. Wisi magna nihil facer insitam qui. Placerat illum qui in sed at. Praesent lectorum ex sollemnes enim qui. Habent dolore est me nobis quam. Sed et consequat est option feugait. Dolor vero ipsum et mutationem eu. Vel notare possim claritas nunc processus. Claritatem in doming quinta euismod lectores.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Ea nobis facilisi decima facilisis eum. Est typi quod nonummy littera non. Placerat quarta duis facer processus hendrerit. Volutpat legere legentis soluta putamus eum. Aliquam te seacula ex facilisis delenit. Exerci parum vero dolor zzril notare. In est lobortis legentis in tincidunt. </p>
<p>In vel usus in dolor suscipit. Sequitur lectorum feugait veniam et quinta. Claritatem facilisis nobis velit in lius. Feugiat nobis iis processus cum blandit. Vulputate usus eu hendrerit ut est. Decima dynamicus ex accumsan dolor autem. Insitam typi molestie praesent ut eleifend. Typi suscipit ut blandit ipsum sequitur. Dolore dignissim tincidunt ut erat nibh. Possim veniam gothica legunt legere wisi. Consuetudium tincidunt odio decima magna quinta. Modo me in consectetuer nunc qui. Nulla soluta futurum nostrud sollemnes parum. Placerat non etiam futurum euismod qui. Aliquip zzril nulla ut claritatem parum. </p>
<p>Lobortis lius parum vel wisi dolore. In exerci esse nulla nunc modo. Aliquip est videntur te typi nibh. Te dolor nam in imperdiet iis. Decima quarta diam facilisis et in. Iriure est iriure eros vero usus. Typi nulla ut enim quinta molestie. Zzril volutpat duis quinta nulla eros. Lectores non euismod delenit diam facilisis. Praesent parum typi at erat dolore. Legunt in typi dolore nulla clari. Wisi magna nihil facer insitam qui. Placerat illum qui in sed at. Praesent lectorum ex sollemnes enim qui. Habent dolore est me nobis quam. Sed et consequat est option feugait. Dolor vero ipsum et mutationem eu. Vel notare possim claritas nunc processus. Claritatem in doming quinta euismod lectores.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_department' => array(
      'und' => array(
        0 => array(
          'value' => 'EOP',
          'format' => NULL,
          'safe_value' => 'EOP',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Lyndon',
          'format' => NULL,
          'safe_value' => 'Lyndon',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'President',
          'format' => NULL,
          'safe_value' => 'President',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Johnson',
          'format' => NULL,
          'safe_value' => 'Johnson',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
    'field_profile_phone' => array(
      'und' => array(
        0 => array(
          'value' => '(555)123-4444',
          'format' => NULL,
          'safe_value' => '(555)123-4444',
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => '90px-37_Lyndon_Johnson_3x4.jpg',
          'uri' => 'public://90px-37_Lyndon_Johnson_3x4.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 3645,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'demo content image',
          'title' => 'demo content image',
          'width' => 90,
          'height' => 120,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['open_gov_contact_person'] = (object) array(
    'exported_path' => 'profile/james-jones',
    'title' => 'James Jones',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1294788829,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'open_gov_contact_person',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque porta tincidunt imperdiet. Phasellus placerat ornare nisl, sed mollis nisl consequat et. Curabitur eu mauris eget erat congue commodo eget sed magna. Sed et dui quis diam dapibus placerat. Proin ornare, nibh dignissim dapibus commodo, dui nisi interdum urna, nec aliquet nibh elit quis dui. Quisque ipsum tellus, ornare at varius sit amet, ultrices eu nibh. Sed vitae nibh purus, mollis scelerisque tortor. Curabitur rhoncus, sem ac varius pellentesque, justo nisl vestibulum magna, eu tempor nulla magna quis eros. Vivamus at consequat eros. Sed nec arcu nec ligula bibendum iaculis. Aenean in arcu ante. Aliquam ultrices, sapien hendrerit aliquam sagittis, libero ipsum pellentesque libero, at tristique augue leo sit amet quam. Nullam bibendum scelerisque neque. Fusce ligula tellus, blandit nec hendrerit sed, convallis eget nisi. Donec non sapien vel nulla convallis dictum.

Phasellus blandit rhoncus sapien, ac laoreet metus dictum ac. Cras non elit nec ligula feugiat dignissim vel id sem. Nam consequat, velit sit amet gravida viverra, lacus dolor sollicitudin ante, quis dignissim justo sapien at odio. Duis gravida risus eget ligula aliquam fermentum. Mauris leo enim, varius vitae venenatis blandit, tempus eu purus. Sed euismod malesuada turpis, ac sollicitudin ante dignissim nec. Phasellus risus leo, cursus scelerisque adipiscing ut, blandit id quam. Cras laoreet euismod eros vel eleifend. Aenean ut lacus in ante rhoncus cursus vel eget ipsum. Nulla sed urna sed lectus posuere iaculis. Nullam nunc nunc, malesuada ut tincidunt a, dignissim eu nisl. Aliquam erat volutpat. Morbi scelerisque nisl eu quam interdum eu volutpat neque facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; ',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque porta tincidunt imperdiet. Phasellus placerat ornare nisl, sed mollis nisl consequat et. Curabitur eu mauris eget erat congue commodo eget sed magna. Sed et dui quis diam dapibus placerat. Proin ornare, nibh dignissim dapibus commodo, dui nisi interdum urna, nec aliquet nibh elit quis dui. Quisque ipsum tellus, ornare at varius sit amet, ultrices eu nibh. Sed vitae nibh purus, mollis scelerisque tortor. Curabitur rhoncus, sem ac varius pellentesque, justo nisl vestibulum magna, eu tempor nulla magna quis eros. Vivamus at consequat eros. Sed nec arcu nec ligula bibendum iaculis. Aenean in arcu ante. Aliquam ultrices, sapien hendrerit aliquam sagittis, libero ipsum pellentesque libero, at tristique augue leo sit amet quam. Nullam bibendum scelerisque neque. Fusce ligula tellus, blandit nec hendrerit sed, convallis eget nisi. Donec non sapien vel nulla convallis dictum.</p>
<p>Phasellus blandit rhoncus sapien, ac laoreet metus dictum ac. Cras non elit nec ligula feugiat dignissim vel id sem. Nam consequat, velit sit amet gravida viverra, lacus dolor sollicitudin ante, quis dignissim justo sapien at odio. Duis gravida risus eget ligula aliquam fermentum. Mauris leo enim, varius vitae venenatis blandit, tempus eu purus. Sed euismod malesuada turpis, ac sollicitudin ante dignissim nec. Phasellus risus leo, cursus scelerisque adipiscing ut, blandit id quam. Cras laoreet euismod eros vel eleifend. Aenean ut lacus in ante rhoncus cursus vel eget ipsum. Nulla sed urna sed lectus posuere iaculis. Nullam nunc nunc, malesuada ut tincidunt a, dignissim eu nisl. Aliquam erat volutpat. Morbi scelerisque nisl eu quam interdum eu volutpat neque facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'James',
          'format' => NULL,
          'safe_value' => 'James',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Deputy Director of Technology',
          'format' => NULL,
          'safe_value' => 'Deputy Director of Technology',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Jones',
          'format' => NULL,
          'safe_value' => 'Jones',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 0,
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'guy_in_suit_2.jpeg',
          'uri' => 'public://guy_in_suit_2.jpeg',
          'filemime' => 'image/jpeg',
          'filesize' => 28657,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'Photo of James Jones',
          'title' => 'Photo of James Jones',
          'width' => 287,
          'height' => 280,
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

  $content['press_contact'] = (object) array(
    'exported_path' => 'profile/carol-press',
    'title' => 'Carol Press',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'profile',
    'language' => 'und',
    'created' => 1297094262,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'press_contact',
    'body' => array(),
    'field_profile_address' => array(
      'und' => array(
        0 => array(
          'value' => '5432 5th St. 
Suite #606
Washington DC 20036',
          'format' => NULL,
          'safe_value' => '5432 5th St. 
Suite #606
Washington DC 20036',
        ),
      ),
    ),
    'field_profile_department' => array(
      'und' => array(
        0 => array(
          'value' => 'Media Relations',
          'format' => NULL,
          'safe_value' => 'Media Relations',
        ),
      ),
    ),
    'field_profile_email' => array(
      'und' => array(
        0 => array(
          'value' => 'cpress@opic.gov',
          'format' => NULL,
          'safe_value' => 'cpress@opic.gov',
        ),
      ),
    ),
    'field_profile_first_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Carol',
          'format' => NULL,
          'safe_value' => 'Carol',
        ),
      ),
    ),
    'field_profile_job_title' => array(
      'und' => array(
        0 => array(
          'value' => 'Director of the Press',
          'format' => NULL,
          'safe_value' => 'Director of the Press',
        ),
      ),
    ),
    'field_profile_last_name' => array(
      'und' => array(
        0 => array(
          'value' => 'Press',
          'format' => NULL,
          'safe_value' => 'Press',
        ),
      ),
    ),
    'field_profile_leadership' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
    'field_profile_phone' => array(
      'und' => array(
        0 => array(
          'value' => '202-341-5555',
          'format' => NULL,
          'safe_value' => '202-341-5555',
        ),
      ),
    ),
    'field_profile_photo' => array(
      'und' => array(
        0 => array(
          'filename' => 'willy_post.wikipedia.jpg',
          'uri' => 'public://willy_post.wikipedia.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 58006,
          'status' => 1,
          'rdf_mapping' => array(),
          'alt' => 'Photo of Carol Press',
          'title' => 'Photo of Carol Press',
          'width' => 640,
          'height' => 954,
        ),
      ),
    ),
    'field_profile_social_media' => array(
      'und' => array(
        0 => array(
          'value' => 'http://twitter.com/inadarei',
          'format' => NULL,
          'safe_value' => 'http://twitter.com/inadarei',
        ),
      ),
    ),
    'field_profile_staff' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );

return $content;
}
