<?php
/**
 * @file
 * openpublic_press_release_demo.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openpublic_press_release_demo_content_defaults() {
  $content = array();

  $content['abc_agency_announces_up_top50_million_for_fuel_cell_research'] = (object) array(
    'exported_path' => 'press-release/abc-agency-announces-50-million-fuel-cell-research',
    'title' => 'ABC Agency Announces up to $50 Million for Fuel Cell Research',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1293738699,
    'comment' => 1,
    'translate' => 0,
    'machine_name' => 'abc_agency_announces_up_top50_million_for_fuel_cell_research',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Lobortis ii in in consectetuer blandit. Esse tation in duis typi duis. Iis vel soluta ea tempor placerat. Parum seacula facilisis legentis id nulla. Consequat nulla nibh sed typi facilisi. Aliquam gothica non ea nobis sit. Investigationes anteposuerit formas id facer dynamicus. Sed vulputate dolore quis quam quarta. Quinta nam commodo cum dolor non. Littera praesent molestie quinta lectores nunc. Qui tincidunt dolor enim erat dolore. Qui me zzril ullamcorper mutationem iusto. Vel legunt decima eum enim in. Possim et in humanitatis vero qui. 

Doming option qui ipsum Investigationes facilisis. Molestie lectorum ex ea clari mazim. Minim ad nunc iis usus gothica. Elit nibh ut amet in illum. Luptatum feugait assum blandit et possim. Modo assum mirum ut nunc futurum. Dolor tempor notare me iusto at. In blandit qui augue at lectores. Lobortis praesent erat duis gothica quis. Nulla lius velit option veniam wisi. Velit sit ut notare autem odio. Dolore delenit nisl nisl qui euismod. Magna laoreet id quam facer est. Facilisis demonstraverunt usus mazim eros suscipit. 

Ut est habent minim iusto facit. Mutationem facilisi in consequat littera mutationem. Gothica nihil nunc molestie ut aliquip. Est iis seacula ut iis parum. Quinta sit vulputate volutpat te videntur. Tempor vulputate ea clari wisi zzril. In futurum in dolor et eum. Elit claram demonstraverunt at legere lobortis. Legentis qui exerci qui esse nobis. Mutationem legunt quam volutpat in claram. Quis typi soluta mutationem eleifend feugiat. Processus legunt feugait option futurum ullamcorper. Ad imperdiet qui et praesent legere. Ut augue zzril litterarum accumsan liber. Congue processus lectorum illum videntur consectetuer. Vero lectorum nobis legunt quam elit.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Lobortis ii in in consectetuer blandit. Esse tation in duis typi duis. Iis vel soluta ea tempor placerat. Parum seacula facilisis legentis id nulla. Consequat nulla nibh sed typi facilisi. Aliquam gothica non ea nobis sit. Investigationes anteposuerit formas id facer dynamicus. Sed vulputate dolore quis quam quarta. Quinta nam commodo cum dolor non. Littera praesent molestie quinta lectores nunc. Qui tincidunt dolor enim erat dolore. Qui me zzril ullamcorper mutationem iusto. Vel legunt decima eum enim in. Possim et in humanitatis vero qui. </p>
<p>Doming option qui ipsum Investigationes facilisis. Molestie lectorum ex ea clari mazim. Minim ad nunc iis usus gothica. Elit nibh ut amet in illum. Luptatum feugait assum blandit et possim. Modo assum mirum ut nunc futurum. Dolor tempor notare me iusto at. In blandit qui augue at lectores. Lobortis praesent erat duis gothica quis. Nulla lius velit option veniam wisi. Velit sit ut notare autem odio. Dolore delenit nisl nisl qui euismod. Magna laoreet id quam facer est. Facilisis demonstraverunt usus mazim eros suscipit. </p>
<p>Ut est habent minim iusto facit. Mutationem facilisi in consequat littera mutationem. Gothica nihil nunc molestie ut aliquip. Est iis seacula ut iis parum. Quinta sit vulputate volutpat te videntur. Tempor vulputate ea clari wisi zzril. In futurum in dolor et eum. Elit claram demonstraverunt at legere lobortis. Legentis qui exerci qui esse nobis. Mutationem legunt quam volutpat in claram. Quis typi soluta mutationem eleifend feugiat. Processus legunt feugait option futurum ullamcorper. Ad imperdiet qui et praesent legere. Ut augue zzril litterarum accumsan liber. Congue processus lectorum illum videntur consectetuer. Vero lectorum nobis legunt quam elit.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['best_practices_for_xyz_policies_highlighted_by_abc_agency_secretary'] = (object) array(
    'exported_path' => 'press-release/best-practices-xyz-policies-highlighted-abc-agency-secretary',
    'title' => 'Best Practices for XYZ Policies Highlighted by ABC Agency Secretary',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1291134990,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'best_practices_for_xyz_policies_highlighted_by_abc_agency_secretary',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Magna erat quarta luptatum et eorum. Sollemnes option est dolore nibh dolor. Dignissim nihil futurum id doming dolore. Assum nihil etiam hendrerit at legentis. Demonstraverunt et congue eum facilisis videntur. Mirum nunc iusto luptatum facit dignissim. Exerci imperdiet nobis cum imperdiet ullamcorper. Mazim minim euismod humanitatis placerat Investigationes. Molestie quinta typi euismod videntur facit. Quod qui assum iis quod congue. Ii est nihil putamus anteposuerit est. Lectorum iusto est euismod formas diam. Vel tation ii decima feugiat odio. Facilisi nunc per volutpat dignissim duis. 

Vel qui soluta nostrud nulla nulla. Enim legere ullamcorper legere clari minim. Augue magna saepius per facer esse. Zzril imperdiet litterarum iriure sequitur erat. Te autem minim dolor facer eum. Iusto facit eleifend quod qui in. Sed autem est facit illum esse. 

Nihil iriure enim clari cum aliquam. Dolore dolor diam dolore in sequitur. Aliquam insitam quarta in illum eum. At dolore elit legere et iis. Volutpat te mazim esse lectores ullamcorper. Habent notare legunt augue habent augue. Mutationem ipsum et blandit in nibh. Futurum iis sequitur ex ea illum. In est possim feugait habent facer. Minim dolore vero facilisi mirum ut. Eu futurum assum consuetudium quod vel. Minim parum tempor minim in insitam. Per iriure praesent dynamicus wisi est. Sed mirum decima est decima ea. 

Luptatum adipiscing vel option nobis claram. Enim te iriure commodo dolore assum. Nostrud delenit blandit claritatem liber ii. Mazim etiam feugiat legere putamus illum. Lius per assum insitam qui te. Ea notare in est ii formas. Ad duis liber claram non erat. Odio quinta putamus eodem etiam zzril. Tempor aliquam lectorum velit magna sit. Videntur quarta sequitur facilisi mutationem dolor. Eleifend in ut nulla aliquam quod. Quod futurum liber iriure esse praesent. Dynamicus luptatum humanitatis volutpat claritas in. Eleifend quinta dolor quod quis molestie. Quarta seacula dignissim nulla quam et.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Magna erat quarta luptatum et eorum. Sollemnes option est dolore nibh dolor. Dignissim nihil futurum id doming dolore. Assum nihil etiam hendrerit at legentis. Demonstraverunt et congue eum facilisis videntur. Mirum nunc iusto luptatum facit dignissim. Exerci imperdiet nobis cum imperdiet ullamcorper. Mazim minim euismod humanitatis placerat Investigationes. Molestie quinta typi euismod videntur facit. Quod qui assum iis quod congue. Ii est nihil putamus anteposuerit est. Lectorum iusto est euismod formas diam. Vel tation ii decima feugiat odio. Facilisi nunc per volutpat dignissim duis. </p>
<p>Vel qui soluta nostrud nulla nulla. Enim legere ullamcorper legere clari minim. Augue magna saepius per facer esse. Zzril imperdiet litterarum iriure sequitur erat. Te autem minim dolor facer eum. Iusto facit eleifend quod qui in. Sed autem est facit illum esse. </p>
<p>Nihil iriure enim clari cum aliquam. Dolore dolor diam dolore in sequitur. Aliquam insitam quarta in illum eum. At dolore elit legere et iis. Volutpat te mazim esse lectores ullamcorper. Habent notare legunt augue habent augue. Mutationem ipsum et blandit in nibh. Futurum iis sequitur ex ea illum. In est possim feugait habent facer. Minim dolore vero facilisi mirum ut. Eu futurum assum consuetudium quod vel. Minim parum tempor minim in insitam. Per iriure praesent dynamicus wisi est. Sed mirum decima est decima ea. </p>
<p>Luptatum adipiscing vel option nobis claram. Enim te iriure commodo dolore assum. Nostrud delenit blandit claritatem liber ii. Mazim etiam feugiat legere putamus illum. Lius per assum insitam qui te. Ea notare in est ii formas. Ad duis liber claram non erat. Odio quinta putamus eodem etiam zzril. Tempor aliquam lectorum velit magna sit. Videntur quarta sequitur facilisi mutationem dolor. Eleifend in ut nulla aliquam quod. Quod futurum liber iriure esse praesent. Dynamicus luptatum humanitatis volutpat claritas in. Eleifend quinta dolor quod quis molestie. Quarta seacula dignissim nulla quam et.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['lyndon_johnson_signs_freedom_of_Information_act'] = (object) array(
    'exported_path' => 'press-release/lyndon-johnson-signs-freedom-information-act',
    'title' => 'Lyndon Johnson signs Freedom of Information Act',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => -110254589,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'lyndon_johnson_signs_freedom_of_Information_act',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'The measure I sign today, S. 1160, revises Section 3 of the Administrative Procedure Acto to provide guidelines Et nunc claram accumsan aliquip notare. Investigationes eum mazim videntur molestie te. Possim hendrerit saepius iusto et lobortis. Nihil ut suscipit autem nihil dolor. Ad quinta autem ea te non. Quam est parum iusto quarta dolor. Mazim nibh decima typi laoreet dynamicus. 

Cum exerci me tincidunt facilisis typi. Autem option litterarum vel claram eum. Investigationes quod doming blandit quod duis. Putamus vulputate vulputate diam facer seacula. Lorem aliquip in gothica nobis autem. Volutpat qui saepius parum dolore enim. Qui dignissim lorem adipiscing dolor facilisis.  Imperdiet habent at formas claritas aliquip. Vel dynamicus claritatem humanitatis et delenit. Duis typi option litterarum ut zzril. Nostrud nobis facer facer gothica feugiat. Molestie minim lectorum duis augue lorem. Nihil lius eorum augue decima in. Legentis eum legunt tempor nobis volutpat. 

Molestie nulla lius et claram etiam. Consequat aliquip iriure nobis ullamcorper anteposuerit. Wisi tincidunt eros formas feugiat ut. Modo qui sit molestie lectorum claram. Duis fiant claritatem facilisi possim legentis. Delenit exerci iis putamus eleifend praesent. Erat nobis veniam qui nobis decima. Consequat duis assum in processus luptatum. Te facilisis decima dolore et processus. Habent tempor adipiscing exerci suscipit claritatem. Gothica tincidunt qui luptatum qui ut. Sed qui Investigationes tempor tation iriure. Lobortis ut facer gothica tempor facilisi. At quam me ut erat facilisi.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>The measure I sign today, S. 1160, revises Section 3 of the Administrative Procedure Acto to provide guidelines Et nunc claram accumsan aliquip notare. Investigationes eum mazim videntur molestie te. Possim hendrerit saepius iusto et lobortis. Nihil ut suscipit autem nihil dolor. Ad quinta autem ea te non. Quam est parum iusto quarta dolor. Mazim nibh decima typi laoreet dynamicus. </p>
<p>Cum exerci me tincidunt facilisis typi. Autem option litterarum vel claram eum. Investigationes quod doming blandit quod duis. Putamus vulputate vulputate diam facer seacula. Lorem aliquip in gothica nobis autem. Volutpat qui saepius parum dolore enim. Qui dignissim lorem adipiscing dolor facilisis.  Imperdiet habent at formas claritas aliquip. Vel dynamicus claritatem humanitatis et delenit. Duis typi option litterarum ut zzril. Nostrud nobis facer facer gothica feugiat. Molestie minim lectorum duis augue lorem. Nihil lius eorum augue decima in. Legentis eum legunt tempor nobis volutpat. </p>
<p>Molestie nulla lius et claram etiam. Consequat aliquip iriure nobis ullamcorper anteposuerit. Wisi tincidunt eros formas feugiat ut. Modo qui sit molestie lectorum claram. Duis fiant claritatem facilisi possim legentis. Delenit exerci iis putamus eleifend praesent. Erat nobis veniam qui nobis decima. Consequat duis assum in processus luptatum. Te facilisis decima dolore et processus. Habent tempor adipiscing exerci suscipit claritatem. Gothica tincidunt qui luptatum qui ut. Sed qui Investigationes tempor tation iriure. Lobortis ut facer gothica tempor facilisi. At quam me ut erat facilisi.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['secretary_issues_statement_on_the_results_of_xyz_program'] = (object) array(
    'exported_path' => 'press-release/secretary-issues-statement-results-xyz-program-implementing-education-reform',
    'title' => 'Secretary Issues Statement on the Results of XYZ Program for Implementing Education Reform',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1293739669,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'secretary_issues_statement_on_the_results_of_xyz_program',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Sed mirum notare soluta ut sollemnes. Augue ullamcorper soluta assum decima in. Possim veniam qui delenit est autem. Legentis qui blandit illum veniam imperdiet. Cum qui ullamcorper sit nisl mutationem. Investigationes in quod legere notare sollemnes. Investigationes parum lobortis putamus sequitur amet. In et vero sequitur congue dolore. Nonummy imperdiet habent nostrud consuetudium videntur. Qui lectorum quod et eorum molestie. Wisi minim duis mazim dignissim facer. Ut littera decima vel enim facer. Ut aliquam consuetudium lorem legentis euismod. Quis enim id facer imperdiet dolore. 

Possim duis claritatem claritatem volutpat saepius. Dolor consequat imperdiet suscipit in tation. Qui ut nunc ii claritas sit. Nulla possim sit habent quod fiant. Ipsum mazim anteposuerit lectores diam sollemnes. Iriure eorum clari nulla iusto iriure. Ad consequat lius litterarum claram quod. Dolor euismod quarta mazim lius dignissim. Vel decima littera zzril lectores claritas. Gothica volutpat ut id ex quarta. Lorem zzril suscipit vel quam delenit. Gothica insitam qui me placerat quinta. Duis legentis qui putamus ii erat. Congue aliquip legunt illum duis ii. 

Duis legentis in et est ad. Cum iriure per anteposuerit sequitur lorem. Putamus demonstraverunt in lobortis hendrerit vel. Qui qui consequat quam tempor futurum. Elit lorem iusto liber littera lorem. Nunc iis mazim zzril demonstraverunt eodem. Nulla Investigationes tempor suscipit consequat diam. Usus erat qui laoreet mirum me. Et ipsum lectores est dolore tincidunt. Saepius qui habent ut et littera. Dolor parum habent legere dolor assum. Mirum doming decima nunc sequitur dolor. Ii consequat congue ipsum qui consuetudium. Lectores laoreet vero possim sequitur claritatem. Facer dolore futurum cum parum claritatem. Qui est gothica quod hendrerit odio. Dolore in facit aliquip ipsum lius.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Sed mirum notare soluta ut sollemnes. Augue ullamcorper soluta assum decima in. Possim veniam qui delenit est autem. Legentis qui blandit illum veniam imperdiet. Cum qui ullamcorper sit nisl mutationem. Investigationes in quod legere notare sollemnes. Investigationes parum lobortis putamus sequitur amet. In et vero sequitur congue dolore. Nonummy imperdiet habent nostrud consuetudium videntur. Qui lectorum quod et eorum molestie. Wisi minim duis mazim dignissim facer. Ut littera decima vel enim facer. Ut aliquam consuetudium lorem legentis euismod. Quis enim id facer imperdiet dolore. </p>
<p>Possim duis claritatem claritatem volutpat saepius. Dolor consequat imperdiet suscipit in tation. Qui ut nunc ii claritas sit. Nulla possim sit habent quod fiant. Ipsum mazim anteposuerit lectores diam sollemnes. Iriure eorum clari nulla iusto iriure. Ad consequat lius litterarum claram quod. Dolor euismod quarta mazim lius dignissim. Vel decima littera zzril lectores claritas. Gothica volutpat ut id ex quarta. Lorem zzril suscipit vel quam delenit. Gothica insitam qui me placerat quinta. Duis legentis qui putamus ii erat. Congue aliquip legunt illum duis ii. </p>
<p>Duis legentis in et est ad. Cum iriure per anteposuerit sequitur lorem. Putamus demonstraverunt in lobortis hendrerit vel. Qui qui consequat quam tempor futurum. Elit lorem iusto liber littera lorem. Nunc iis mazim zzril demonstraverunt eodem. Nulla Investigationes tempor suscipit consequat diam. Usus erat qui laoreet mirum me. Et ipsum lectores est dolore tincidunt. Saepius qui habent ut et littera. Dolor parum habent legere dolor assum. Mirum doming decima nunc sequitur dolor. Ii consequat congue ipsum qui consuetudium. Lectores laoreet vero possim sequitur claritatem. Facer dolore futurum cum parum claritatem. Qui est gothica quod hendrerit odio. Dolore in facit aliquip ipsum lius.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['taxcode_pressrelease'] = (object) array(
    'exported_path' => 'press-release/congress-moves-bipartisan-effort-simplify-us-tax-code',
    'title' => 'Congress Moves on Bipartisan Effort to Simplify US Tax Code',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1296514469,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'taxcode_pressrelease',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Sed typi typi sed duis eleifend. Ea seacula euismod me sed notare. Processus ea adipiscing qui in parum. Cum dolore nostrud non dynamicus vel. Iis qui euismod odio veniam ut. Legentis consectetuer nobis usus vel duis. Formas et mutationem per iriure saepius. 

Quis consuetudium feugait nunc nobis notare. Nunc dignissim ut ullamcorper nulla nihil. Nulla nobis elit ullamcorper consectetuer sit. Facit ii humanitatis consectetuer me legere. Tempor eleifend quarta lius habent sed. Gothica iis insitam eodem vero aliquam. Tincidunt tation est typi typi liber. 

Typi in etiam eorum et sollemnes. Ex nunc magna zzril sollemnes iriure. Illum in praesent dolore dignissim sequitur. Est lius mirum mazim magna notare. Possim vulputate quarta eu eorum quis. Gothica putamus duis decima aliquam adipiscing. Ea facilisi velit illum eorum possim. 

Sollemnes quis quis lectorum facilisis per. Sed non humanitatis liber quis futurum. Iusto sequitur tincidunt lobortis vero nobis. Qui congue cum non tempor legere. Assum formas gothica suscipit aliquam laoreet. Liber demonstraverunt suscipit consuetudium lius lectorum. Qui claritatem non sed est feugait. 

In in nunc litterarum clari typi. Placerat luptatum processus ullamcorper exerci diam. Magna euismod consectetuer qui nunc tempor.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Sed typi typi sed duis eleifend. Ea seacula euismod me sed notare. Processus ea adipiscing qui in parum. Cum dolore nostrud non dynamicus vel. Iis qui euismod odio veniam ut. Legentis consectetuer nobis usus vel duis. Formas et mutationem per iriure saepius. </p>
<p>Quis consuetudium feugait nunc nobis notare. Nunc dignissim ut ullamcorper nulla nihil. Nulla nobis elit ullamcorper consectetuer sit. Facit ii humanitatis consectetuer me legere. Tempor eleifend quarta lius habent sed. Gothica iis insitam eodem vero aliquam. Tincidunt tation est typi typi liber. </p>
<p>Typi in etiam eorum et sollemnes. Ex nunc magna zzril sollemnes iriure. Illum in praesent dolore dignissim sequitur. Est lius mirum mazim magna notare. Possim vulputate quarta eu eorum quis. Gothica putamus duis decima aliquam adipiscing. Ea facilisi velit illum eorum possim. </p>
<p>Sollemnes quis quis lectorum facilisis per. Sed non humanitatis liber quis futurum. Iusto sequitur tincidunt lobortis vero nobis. Qui congue cum non tempor legere. Assum formas gothica suscipit aliquam laoreet. Liber demonstraverunt suscipit consuetudium lius lectorum. Qui claritatem non sed est feugait. </p>
<p>In in nunc litterarum clari typi. Placerat luptatum processus ullamcorper exerci diam. Magna euismod consectetuer qui nunc tempor.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['this_is_an_example_of_press_release'] = (object) array(
    'exported_path' => 'press-release/example-press-release',
    'title' => 'This is an Example of a Press Release ',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1293726990,
    'comment' => 0,
    'translate' => 0,
    'machine_name' => 'this_is_an_example_of_press_release',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'This was created using the a press release content type. Ii tempor dolore tempor claritas hendrerit. Consequat aliquam decima aliquam claritas eodem. Ullamcorper mazim usus et iis mutationem. Consectetuer anteposuerit delenit quarta mazim placerat. Ea decima praesent ut praesent nobis. Nonummy quinta claram tincidunt sollemnes quarta. Nulla notare accumsan velit qui ex. Feugiat nam iriure volutpat elit mutationem. Sit dynamicus liber blandit claritatem consequat. Quod non typi consectetuer claritatem dolore. Ullamcorper qui aliquam quis claritatem dignissim. Iusto exerci at option aliquam in. Nibh sequitur augue non typi feugait. Consequat duis eorum quam euismod claritas. 

Consuetudium possim possim processus formas insitam. Nobis nunc doming laoreet est doming. At et nibh parum iriure iusto. Decima qui nam facit ex parum. Et esse sit ullamcorper parum assum. Wisi in eu ii sit ea. Legunt eodem dolore at diam anteposuerit. 

In iriure delenit doming futurum demonstraverunt. Magna et nunc quod Investigationes adipiscing. Eodem mirum amet per mirum hendrerit. Sollemnes accumsan notare accumsan dolore nunc. Quam lobortis ii possim insitam nulla. Assum in dolor facilisi eodem soluta. Molestie illum in ipsum anteposuerit ut. 

Tempor qui possim mazim me assum.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>This was created using the a press release content type. Ii tempor dolore tempor claritas hendrerit. Consequat aliquam decima aliquam claritas eodem. Ullamcorper mazim usus et iis mutationem. Consectetuer anteposuerit delenit quarta mazim placerat. Ea decima praesent ut praesent nobis. Nonummy quinta claram tincidunt sollemnes quarta. Nulla notare accumsan velit qui ex. Feugiat nam iriure volutpat elit mutationem. Sit dynamicus liber blandit claritatem consequat. Quod non typi consectetuer claritatem dolore. Ullamcorper qui aliquam quis claritatem dignissim. Iusto exerci at option aliquam in. Nibh sequitur augue non typi feugait. Consequat duis eorum quam euismod claritas. </p>
<p>Consuetudium possim possim processus formas insitam. Nobis nunc doming laoreet est doming. At et nibh parum iriure iusto. Decima qui nam facit ex parum. Et esse sit ullamcorper parum assum. Wisi in eu ii sit ea. Legunt eodem dolore at diam anteposuerit. </p>
<p>In iriure delenit doming futurum demonstraverunt. Magna et nunc quod Investigationes adipiscing. Eodem mirum amet per mirum hendrerit. Sollemnes accumsan notare accumsan dolore nunc. Quam lobortis ii possim insitam nulla. Assum in dolor facilisi eodem soluta. Molestie illum in ipsum anteposuerit ut. </p>
<p>Tempor qui possim mazim me assum.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['whitehouse_issues_open_government_directive'] = (object) array(
    'exported_path' => 'press-release/whitehouse-issues-open-government-directive',
    'title' => 'Whitehouse issues Open Government Directive',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'press_release',
    'language' => 'und',
    'created' => 1260285616,
    'comment' => 1,
    'translate' => 0,
    'machine_name' => 'whitehouse_issues_open_government_directive',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Diam accumsan nihil vel eorum ex. Decima anteposuerit sollemnes dynamicus dolor demonstraverunt. Iusto claritas eorum facilisis illum est. Soluta parum qui quam duis facilisi. Option in legentis amet legunt nihil. Quod nisl etiam mirum volutpat sequitur. Seacula notare erat amet amet habent. Zzril humanitatis ipsum enim ullamcorper lobortis. Parum diam dolore facilisi soluta te. Zzril quam eleifend vel duis videntur. Enim delenit Investigationes laoreet nihil clari. Lectorum autem nisl delenit nam te. Legere humanitatis clari molestie iriure nonummy. Notare nunc tincidunt ea est commodo. 

Wisi delenit claritas assum iusto qui. Zzril commodo te tincidunt humanitatis placerat. Sollemnes nihil eodem claritatem nunc amet. Minim cum et lius putamus in. Et facer nonummy lius litterarum quam. Hendrerit iis ipsum consequat ea facer. Adipiscing vel parum insitam ut typi. Magna nobis dynamicus eodem non euismod. Et lorem dolore usus modo quis. Seacula anteposuerit et esse eum ex. Parum nihil duis demonstraverunt nostrud ex. Delenit tempor iusto odio litterarum fiant. Per in nulla mirum facilisi dolore. Investigationes in nulla molestie molestie humanitatis. 

Consequat illum quinta et doming ipsum. Augue mazim facilisi illum quis vel. Vero quod qui amet mirum lorem. Clari molestie wisi usus tempor quis. Fiant nonummy tempor sit delenit dynamicus. Ullamcorper quod usus eum nostrud tation. Dolore legunt saepius eum legere dolor. Ut litterarum amet facilisis notare futurum. Anteposuerit suscipit futurum legere in ut. Facer litterarum possim mutationem ut suscipit. Veniam odio in usus eodem aliquip. Consuetudium esse nulla volutpat non claritatem. Sollemnes quam mazim nihil est dolor. Minim quod demonstraverunt possim futurum imperdiet. 

Claritas decima hendrerit facilisi amet futurum. Consequat at consuetudium assum eleifend laoreet. Accumsan quam zzril usus clari eodem. Nobis legunt tation option ut erat. Vel molestie ad erat quod imperdiet. Parum decima vel nisl sollemnes typi. Vero quarta in hendrerit claram modo. 

Humanitatis hendrerit dolore ullamcorper facit dolore. Parum illum veniam nostrud liber soluta. Accumsan exerci in nisl anteposuerit adipiscing. Quis lorem illum lorem suscipit magna. Minim et tation est dolor lobortis. Vulputate facilisis lobortis molestie ea nunc. Lectores consuetudium dignissim quam quis quis. Typi mutationem wisi dolore putamus cum.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Diam accumsan nihil vel eorum ex. Decima anteposuerit sollemnes dynamicus dolor demonstraverunt. Iusto claritas eorum facilisis illum est. Soluta parum qui quam duis facilisi. Option in legentis amet legunt nihil. Quod nisl etiam mirum volutpat sequitur. Seacula notare erat amet amet habent. Zzril humanitatis ipsum enim ullamcorper lobortis. Parum diam dolore facilisi soluta te. Zzril quam eleifend vel duis videntur. Enim delenit Investigationes laoreet nihil clari. Lectorum autem nisl delenit nam te. Legere humanitatis clari molestie iriure nonummy. Notare nunc tincidunt ea est commodo. </p>
<p>Wisi delenit claritas assum iusto qui. Zzril commodo te tincidunt humanitatis placerat. Sollemnes nihil eodem claritatem nunc amet. Minim cum et lius putamus in. Et facer nonummy lius litterarum quam. Hendrerit iis ipsum consequat ea facer. Adipiscing vel parum insitam ut typi. Magna nobis dynamicus eodem non euismod. Et lorem dolore usus modo quis. Seacula anteposuerit et esse eum ex. Parum nihil duis demonstraverunt nostrud ex. Delenit tempor iusto odio litterarum fiant. Per in nulla mirum facilisi dolore. Investigationes in nulla molestie molestie humanitatis. </p>
<p>Consequat illum quinta et doming ipsum. Augue mazim facilisi illum quis vel. Vero quod qui amet mirum lorem. Clari molestie wisi usus tempor quis. Fiant nonummy tempor sit delenit dynamicus. Ullamcorper quod usus eum nostrud tation. Dolore legunt saepius eum legere dolor. Ut litterarum amet facilisis notare futurum. Anteposuerit suscipit futurum legere in ut. Facer litterarum possim mutationem ut suscipit. Veniam odio in usus eodem aliquip. Consuetudium esse nulla volutpat non claritatem. Sollemnes quam mazim nihil est dolor. Minim quod demonstraverunt possim futurum imperdiet. </p>
<p>Claritas decima hendrerit facilisi amet futurum. Consequat at consuetudium assum eleifend laoreet. Accumsan quam zzril usus clari eodem. Nobis legunt tation option ut erat. Vel molestie ad erat quod imperdiet. Parum decima vel nisl sollemnes typi. Vero quarta in hendrerit claram modo. </p>
<p>Humanitatis hendrerit dolore ullamcorper facit dolore. Parum illum veniam nostrud liber soluta. Accumsan exerci in nisl anteposuerit adipiscing. Quis lorem illum lorem suscipit magna. Minim et tation est dolor lobortis. Vulputate facilisis lobortis molestie ea nunc. Lectores consuetudium dignissim quam quis quis. Typi mutationem wisi dolore putamus cum.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

return $content;
}
