<?php
/**
 * @file
 * openpublic_blog_demo.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openpublic_blog_demo_content_defaults() {
  $content = array();

  $content['abc_agency_releases_public_datasets_online'] = (object) array(
    'exported_path' => 'blog/2010-12-30/abc-agency-releases-public-datasets-online',
    'title' => 'ABC Agency releases Public Datasets Online',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'blog_entry',
    'language' => 'und',
    'created' => 1293721196,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'abc_agency_releases_public_datasets_online',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Volutpat quam ut quarta mutationem dolore. Eu odio ullamcorper eodem demonstraverunt dolor. Illum quam qui demonstraverunt insitam nulla. Aliquam mirum notare fiant futurum aliquip. Lius ut vel ullamcorper dolor consequat. Sit dolor consuetudium vel quinta wisi. Decima sequitur sollemnes quarta sit ullamcorper. Anteposuerit sequitur veniam est putamus possim. Nam vel suscipit habent humanitatis doming. Option consequat delenit dolore decima amet. Quis magna qui nam non soluta. Sit notare sequitur veniam facit feugait. Facilisis nunc dolor in claritas nunc. Adipiscing magna erat consectetuer usus esse. 

At molestie quis vulputate zzril parum. Investigationes possim adipiscing formas per zzril. Vero dolor fiant est wisi odio. Possim legere nulla option iriure dolore. Dolore parum nisl demonstraverunt id saepius. Tincidunt claritatem quod quam in eum. Dolore parum seacula nonummy parum qui. Eodem nobis claritas consequat modo notare. Doming vel in option ea in. Ipsum in mirum possim et tempor. Augue ut et litterarum insitam ea. Legentis congue accumsan humanitatis decima quam. Ut laoreet dolor eros in lorem. Assum augue legentis elit typi lectorum. 

Quinta augue iusto lobortis claritatem nihil. Illum claritatem adipiscing tation demonstraverunt dynamicus. Facit exerci putamus molestie sit insitam. Facit tincidunt tincidunt at saepius sequitur. Autem doming iis commodo laoreet modo. In gothica habent typi doming dolor. Notare demonstraverunt quam facit habent duis. Nam elit et decima et wisi. Eu euismod eodem modo ad in. Assum diam facer sollemnes Investigationes usus. Volutpat lobortis quam laoreet usus nunc. Laoreet in in gothica in lius. In quod mutationem odio dolore est. Mirum iriure soluta te possim aliquip. 

In duis suscipit typi vero option. Vel humanitatis anteposuerit legere mutationem tation. Quam typi claritatem dignissim id assum. Quod dynamicus ii nibh wisi legentis. Qui nunc feugiat claritatem vel demonstraverunt. Seacula feugait quis wisi sollemnes legere. Dynamicus magna me demonstraverunt ullamcorper vero. Iriure vel eorum sequitur putamus parum. Luptatum decima velit eleifend lectorum eodem. Facer nulla aliquam est vulputate aliquip. Placerat gothica zzril illum modo Investigationes. Ii velit possim legere quis iis. Dolore processus litterarum ullamcorper typi consequat. Usus ad ut sit nibh laoreet. 

Autem habent possim erat lius typi. Sollemnes littera nostrud veniam nulla modo. Nostrud diam vel est nonummy qui. Vel iis humanitatis illum Investigationes in. Dynamicus diam illum in processus typi. Decima mazim enim insitam anteposuerit litterarum.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Volutpat quam ut quarta mutationem dolore. Eu odio ullamcorper eodem demonstraverunt dolor. Illum quam qui demonstraverunt insitam nulla. Aliquam mirum notare fiant futurum aliquip. Lius ut vel ullamcorper dolor consequat. Sit dolor consuetudium vel quinta wisi. Decima sequitur sollemnes quarta sit ullamcorper. Anteposuerit sequitur veniam est putamus possim. Nam vel suscipit habent humanitatis doming. Option consequat delenit dolore decima amet. Quis magna qui nam non soluta. Sit notare sequitur veniam facit feugait. Facilisis nunc dolor in claritas nunc. Adipiscing magna erat consectetuer usus esse. </p>
<p>At molestie quis vulputate zzril parum. Investigationes possim adipiscing formas per zzril. Vero dolor fiant est wisi odio. Possim legere nulla option iriure dolore. Dolore parum nisl demonstraverunt id saepius. Tincidunt claritatem quod quam in eum. Dolore parum seacula nonummy parum qui. Eodem nobis claritas consequat modo notare. Doming vel in option ea in. Ipsum in mirum possim et tempor. Augue ut et litterarum insitam ea. Legentis congue accumsan humanitatis decima quam. Ut laoreet dolor eros in lorem. Assum augue legentis elit typi lectorum. </p>
<p>Quinta augue iusto lobortis claritatem nihil. Illum claritatem adipiscing tation demonstraverunt dynamicus. Facit exerci putamus molestie sit insitam. Facit tincidunt tincidunt at saepius sequitur. Autem doming iis commodo laoreet modo. In gothica habent typi doming dolor. Notare demonstraverunt quam facit habent duis. Nam elit et decima et wisi. Eu euismod eodem modo ad in. Assum diam facer sollemnes Investigationes usus. Volutpat lobortis quam laoreet usus nunc. Laoreet in in gothica in lius. In quod mutationem odio dolore est. Mirum iriure soluta te possim aliquip. </p>
<p>In duis suscipit typi vero option. Vel humanitatis anteposuerit legere mutationem tation. Quam typi claritatem dignissim id assum. Quod dynamicus ii nibh wisi legentis. Qui nunc feugiat claritatem vel demonstraverunt. Seacula feugait quis wisi sollemnes legere. Dynamicus magna me demonstraverunt ullamcorper vero. Iriure vel eorum sequitur putamus parum. Luptatum decima velit eleifend lectorum eodem. Facer nulla aliquam est vulputate aliquip. Placerat gothica zzril illum modo Investigationes. Ii velit possim legere quis iis. Dolore processus litterarum ullamcorper typi consequat. Usus ad ut sit nibh laoreet. </p>
<p>Autem habent possim erat lius typi. Sollemnes littera nostrud veniam nulla modo. Nostrud diam vel est nonummy qui. Vel iis humanitatis illum Investigationes in. Dynamicus diam illum in processus typi. Decima mazim enim insitam anteposuerit litterarum.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['congress_debates_tax_cuts'] = (object) array(
    'exported_path' => 'blog/2010-12-30/congress-debates-tax-cuts',
    'title' => 'Congress Debates Tax Cuts',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'blog_entry',
    'language' => 'und',
    'created' => 1293729205,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'congress_debates_tax_cuts',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Dolore saepius cum nostrud dynamicus vulputate. Diam clari quarta claram quam nunc. Facilisi in quod zzril clari legunt. Investigationes adipiscing claritatem lius typi euismod. Eorum clari nulla ea doming quam. Liber qui tincidunt minim option ullamcorper. Quinta lobortis ut typi velit ullamcorper. 

Gothica qui option dolore adipiscing nunc. Erat nisl quam dolor nulla veniam. Quam delenit illum te quam lius. Legunt assum assum parum veniam te. Molestie eros lectorum seacula est dolore. Veniam quod parum soluta anteposuerit demonstraverunt. Erat exerci littera duis hendrerit eodem. 

Lobortis eorum nihil demonstraverunt videntur accumsan. Quam formas duis laoreet me nobis. Processus nunc per te in notare. Illum sequitur est consectetuer nulla futurum. In vel insitam nostrud quod qui. Eorum qui qui gothica exerci vulputate. Claritatem vulputate saepius futurum litterarum vel. 

Praesent sollemnes seacula ut erat et. Nobis nam luptatum claritas usus qui. Quam parum aliquam notare notare id. Vulputate Investigationes nihil magna me ut. Ii suscipit sed esse dignissim littera. Cum elit qui illum facilisi tation. Ipsum anteposuerit id notare nunc eorum. 

Aliquam id odio accumsan eu qui. Et luptatum lorem formas dolor litterarum. Claritatem nunc sed putamus amet qui. Qui molestie claritatem euismod claritas littera. Imperdiet molestie lectores placerat veniam lectorum. Vel quinta dolore et non duis. Quam ii doming iis dolore fiant. 

Veniam facit possim amet veniam consectetuer. Nisl qui quis lorem et claritas.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Dolore saepius cum nostrud dynamicus vulputate. Diam clari quarta claram quam nunc. Facilisi in quod zzril clari legunt. Investigationes adipiscing claritatem lius typi euismod. Eorum clari nulla ea doming quam. Liber qui tincidunt minim option ullamcorper. Quinta lobortis ut typi velit ullamcorper. </p>
<p>Gothica qui option dolore adipiscing nunc. Erat nisl quam dolor nulla veniam. Quam delenit illum te quam lius. Legunt assum assum parum veniam te. Molestie eros lectorum seacula est dolore. Veniam quod parum soluta anteposuerit demonstraverunt. Erat exerci littera duis hendrerit eodem. </p>
<p>Lobortis eorum nihil demonstraverunt videntur accumsan. Quam formas duis laoreet me nobis. Processus nunc per te in notare. Illum sequitur est consectetuer nulla futurum. In vel insitam nostrud quod qui. Eorum qui qui gothica exerci vulputate. Claritatem vulputate saepius futurum litterarum vel. </p>
<p>Praesent sollemnes seacula ut erat et. Nobis nam luptatum claritas usus qui. Quam parum aliquam notare notare id. Vulputate Investigationes nihil magna me ut. Ii suscipit sed esse dignissim littera. Cum elit qui illum facilisi tation. Ipsum anteposuerit id notare nunc eorum. </p>
<p>Aliquam id odio accumsan eu qui. Et luptatum lorem formas dolor litterarum. Claritatem nunc sed putamus amet qui. Qui molestie claritatem euismod claritas littera. Imperdiet molestie lectores placerat veniam lectorum. Vel quinta dolore et non duis. Quam ii doming iis dolore fiant. </p>
<p>Veniam facit possim amet veniam consectetuer. Nisl qui quis lorem et claritas.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

  $content['five_recent _abcs_agency_achievements_you_should_know_about'] = (object) array(
    'exported_path' => 'blog/2010-12-30/5-recent-abc-agency-achievements-you-should-know-about',
    'title' => '5 Recent ABC Agency Achievements You Should Know About',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'blog_entry',
    'language' => 'und',
    'created' => 1293737618,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'five_recent _abcs_agency_achievements_you_should_know_about',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Soluta exerci dolore nulla ut odio. Legunt sit quis option feugiat dolore. Decima minim duis wisi blandit parum. Placerat legere doming eodem ex facit. Lius nulla quis quam consuetudium claritas. Wisi option adipiscing sed enim litterarum. Ipsum lobortis veniam formas iis humanitatis. Videntur consuetudium ad exerci iis facer. Suscipit anteposuerit facilisis nibh iis doming. Facilisi consectetuer ex vero commodo iusto. Iusto molestie facilisi assum legere eros. Claritatem qui ipsum est dolore et. Litterarum esse formas etiam iis decima. Adipiscing humanitatis duis quis suscipit claritatem. 

Nibh amet saepius iusto odio in. Eorum esse usus hendrerit iriure vel. Vulputate nostrud congue illum eorum mutationem. Sollemnes possim tempor elit nam blandit. Non consequat processus imperdiet nonummy vulputate. Facit ut molestie placerat usus iusto. Gothica luptatum euismod legunt Investigationes littera. Claram consequat saepius aliquam delenit esse. Odio decima consequat claritas claram est. Lius parum feugiat demonstraverunt facilisi ad. Laoreet qui imperdiet suscipit per nobis. Typi iriure laoreet per at claram. Eorum iriure lectores cum laoreet legere. Aliquip euismod eu dignissim legere parum. 

Hendrerit consequat claram ut est erat. Littera facer iusto velit facit imperdiet. Futurum velit consuetudium est eum eu. Processus vulputate feugait parum minim et. Claram parum aliquip parum et sed. Dolore et mirum augue parum velit. Lobortis iusto vero lobortis tincidunt et. 

Vulputate adipiscing mazim fiant dignissim non. Notare placerat nibh eleifend id dolore. Legunt adipiscing illum quam nunc legunt. Dynamicus consuetudium feugiat ut sollemnes dignissim.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Soluta exerci dolore nulla ut odio. Legunt sit quis option feugiat dolore. Decima minim duis wisi blandit parum. Placerat legere doming eodem ex facit. Lius nulla quis quam consuetudium claritas. Wisi option adipiscing sed enim litterarum. Ipsum lobortis veniam formas iis humanitatis. Videntur consuetudium ad exerci iis facer. Suscipit anteposuerit facilisis nibh iis doming. Facilisi consectetuer ex vero commodo iusto. Iusto molestie facilisi assum legere eros. Claritatem qui ipsum est dolore et. Litterarum esse formas etiam iis decima. Adipiscing humanitatis duis quis suscipit claritatem. </p>
<p>Nibh amet saepius iusto odio in. Eorum esse usus hendrerit iriure vel. Vulputate nostrud congue illum eorum mutationem. Sollemnes possim tempor elit nam blandit. Non consequat processus imperdiet nonummy vulputate. Facit ut molestie placerat usus iusto. Gothica luptatum euismod legunt Investigationes littera. Claram consequat saepius aliquam delenit esse. Odio decima consequat claritas claram est. Lius parum feugiat demonstraverunt facilisi ad. Laoreet qui imperdiet suscipit per nobis. Typi iriure laoreet per at claram. Eorum iriure lectores cum laoreet legere. Aliquip euismod eu dignissim legere parum. </p>
<p>Hendrerit consequat claram ut est erat. Littera facer iusto velit facit imperdiet. Futurum velit consuetudium est eum eu. Processus vulputate feugait parum minim et. Claram parum aliquip parum et sed. Dolore et mirum augue parum velit. Lobortis iusto vero lobortis tincidunt et. </p>
<p>Vulputate adipiscing mazim fiant dignissim non. Notare placerat nibh eleifend id dolore. Legunt adipiscing illum quam nunc legunt. Dynamicus consuetudium feugiat ut sollemnes dignissim.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
  );

return $content;
}
